#!/bin/sh

# Do ARGINOUT versions
make TO_BUILD=STATICLIB BUILD_VERSION=DEBUG INPUT_AND_OUTPUT=ARGINOUT
make TO_BUILD=STATICLIB BUILD_VERSION=RELEASE INPUT_AND_OUTPUT=ARGINOUT
make TO_BUILD=SHAREDLIB BUILD_VERSION=DEBUG INPUT_AND_OUTPUT=ARGINOUT
make TO_BUILD=SHAREDLIB BUILD_VERSION=RELEASE INPUT_AND_OUTPUT=ARGINOUT

# Do ARGINBOTHOUT versions
make TO_BUILD=STATICLIB BUILD_VERSION=DEBUG INPUT_AND_OUTPUT=ARGINBOTHOUT
make TO_BUILD=STATICLIB BUILD_VERSION=RELEASE INPUT_AND_OUTPUT=ARGINBOTHOUT
make TO_BUILD=SHAREDLIB BUILD_VERSION=DEBUG INPUT_AND_OUTPUT=ARGINBOTHOUT
make TO_BUILD=SHAREDLIB BUILD_VERSION=RELEASE INPUT_AND_OUTPUT=ARGINBOTHOUT

# Do FILEINOUT versions
make TO_BUILD=STATICLIB BUILD_VERSION=DEBUG INPUT_AND_OUTPUT=FILEINOUT
make TO_BUILD=STATICLIB BUILD_VERSION=RELEASE INPUT_AND_OUTPUT=FILEINOUT
make TO_BUILD=SHAREDLIB BUILD_VERSION=DEBUG INPUT_AND_OUTPUT=FILEINOUT
make TO_BUILD=SHAREDLIB BUILD_VERSION=RELEASE INPUT_AND_OUTPUT=FILEINOUT
