var annotated_dup =
[
    [ "nanoflann", "d8/d1a/namespacenanoflann.html", [
      [ "array_or_vector", "dd/d12/structnanoflann_1_1array__or__vector.html", "dd/d12/structnanoflann_1_1array__or__vector" ],
      [ "array_or_vector<-1, T >", "df/d7b/structnanoflann_1_1array__or__vector_3-1_00_01T_01_4.html", "df/d7b/structnanoflann_1_1array__or__vector_3-1_00_01T_01_4" ],
      [ "has_assign", "d0/d8d/structnanoflann_1_1has__assign.html", null ],
      [ "has_assign< T, decltype((void) std::declval< T >().assign(1, 0), 0)>", "da/dee/structnanoflann_1_1has__assign_3_01T_00_01decltype_07_07void_08_01std_1_1declval_3_01T_01_4_07_0384656df8feb37b62ef12dfcd439e93e.html", null ],
      [ "has_resize", "db/d13/structnanoflann_1_1has__resize.html", null ],
      [ "has_resize< T, decltype((void) std::declval< T >().resize(1), 0)>", "da/d86/structnanoflann_1_1has__resize_3_01T_00_01decltype_07_07void_08_01std_1_1declval_3_01T_01_4_07_08_8resize_071_08_00_010_08_4.html", null ],
      [ "IndexDist_Sorter", "d0/d61/structnanoflann_1_1IndexDist__Sorter.html", "d0/d61/structnanoflann_1_1IndexDist__Sorter" ],
      [ "KDTreeBaseClass", "df/d14/classnanoflann_1_1KDTreeBaseClass.html", "df/d14/classnanoflann_1_1KDTreeBaseClass" ],
      [ "KDTreeEigenMatrixAdaptor", "d8/d4a/structnanoflann_1_1KDTreeEigenMatrixAdaptor.html", "d8/d4a/structnanoflann_1_1KDTreeEigenMatrixAdaptor" ],
      [ "KDTreeSingleIndexAdaptor", "de/dd0/classnanoflann_1_1KDTreeSingleIndexAdaptor.html", "de/dd0/classnanoflann_1_1KDTreeSingleIndexAdaptor" ],
      [ "KDTreeSingleIndexAdaptorParams", "d5/d47/structnanoflann_1_1KDTreeSingleIndexAdaptorParams.html", "d5/d47/structnanoflann_1_1KDTreeSingleIndexAdaptorParams" ],
      [ "KDTreeSingleIndexDynamicAdaptor", "d4/d9e/classnanoflann_1_1KDTreeSingleIndexDynamicAdaptor.html", "d4/d9e/classnanoflann_1_1KDTreeSingleIndexDynamicAdaptor" ],
      [ "KDTreeSingleIndexDynamicAdaptor_", "d1/db4/classnanoflann_1_1KDTreeSingleIndexDynamicAdaptor__.html", "d1/db4/classnanoflann_1_1KDTreeSingleIndexDynamicAdaptor__" ],
      [ "KNNResultSet", "db/d6e/classnanoflann_1_1KNNResultSet.html", "db/d6e/classnanoflann_1_1KNNResultSet" ],
      [ "L1_Adaptor", "dc/d49/structnanoflann_1_1L1__Adaptor.html", "dc/d49/structnanoflann_1_1L1__Adaptor" ],
      [ "L2_Adaptor", "d4/df1/structnanoflann_1_1L2__Adaptor.html", "d4/df1/structnanoflann_1_1L2__Adaptor" ],
      [ "L2_Simple_Adaptor", "db/d93/structnanoflann_1_1L2__Simple__Adaptor.html", "db/d93/structnanoflann_1_1L2__Simple__Adaptor" ],
      [ "Metric", "df/d87/structnanoflann_1_1Metric.html", null ],
      [ "metric_L1", "d7/d60/structnanoflann_1_1metric__L1.html", "d7/d60/structnanoflann_1_1metric__L1" ],
      [ "metric_L2", "d2/d3f/structnanoflann_1_1metric__L2.html", "d2/d3f/structnanoflann_1_1metric__L2" ],
      [ "metric_L2_Simple", "de/d10/structnanoflann_1_1metric__L2__Simple.html", "de/d10/structnanoflann_1_1metric__L2__Simple" ],
      [ "metric_SO2", "d8/d87/structnanoflann_1_1metric__SO2.html", "d8/d87/structnanoflann_1_1metric__SO2" ],
      [ "metric_SO3", "dc/d81/structnanoflann_1_1metric__SO3.html", "dc/d81/structnanoflann_1_1metric__SO3" ],
      [ "PooledAllocator", "d0/d98/classnanoflann_1_1PooledAllocator.html", "d0/d98/classnanoflann_1_1PooledAllocator" ],
      [ "RadiusResultSet", "d0/d07/classnanoflann_1_1RadiusResultSet.html", "d0/d07/classnanoflann_1_1RadiusResultSet" ],
      [ "ResultItem", "d8/de3/structnanoflann_1_1ResultItem.html", "d8/de3/structnanoflann_1_1ResultItem" ],
      [ "RKNNResultSet", "d9/d79/classnanoflann_1_1RKNNResultSet.html", "d9/d79/classnanoflann_1_1RKNNResultSet" ],
      [ "SearchParameters", "d8/d4b/structnanoflann_1_1SearchParameters.html", "d8/d4b/structnanoflann_1_1SearchParameters" ],
      [ "SO2_Adaptor", "dd/d9f/structnanoflann_1_1SO2__Adaptor.html", "dd/d9f/structnanoflann_1_1SO2__Adaptor" ],
      [ "SO3_Adaptor", "d5/d67/structnanoflann_1_1SO3__Adaptor.html", "d5/d67/structnanoflann_1_1SO3__Adaptor" ]
    ] ],
    [ "array", "d2/d41/classarray.html", "d2/d41/classarray" ],
    [ "bad_alloc", "d5/d15/classbad__alloc.html", null ],
    [ "CA2DIShape", "d2/d0f/classCA2DIShape.html", "d2/d0f/classCA2DIShape" ],
    [ "CA2DShape", "d9/d0e/classCA2DShape.html", "d9/d0e/classCA2DShape" ],
    [ "CACoastLandform", "d2/de0/classCACoastLandform.html", "d2/de0/classCACoastLandform" ],
    [ "CConfiguration", "dc/d01/classCConfiguration.html", "dc/d01/classCConfiguration" ],
    [ "CGeom2DIPoint", "d6/d0d/classCGeom2DIPoint.html", "d6/d0d/classCGeom2DIPoint" ],
    [ "CGeom2DPoint", "d5/d4e/classCGeom2DPoint.html", "d5/d4e/classCGeom2DPoint" ],
    [ "CGeomCell", "d1/dd9/classCGeomCell.html", "d1/dd9/classCGeomCell" ],
    [ "CGeomCoastPolygon", "df/d45/classCGeomCoastPolygon.html", "df/d45/classCGeomCoastPolygon" ],
    [ "CGeomILine", "dd/dc1/classCGeomILine.html", "dd/dc1/classCGeomILine" ],
    [ "CGeomLine", "d7/dd3/classCGeomLine.html", "d7/dd3/classCGeomLine" ],
    [ "CGeomMultiLine", "d0/d89/classCGeomMultiLine.html", "d0/d89/classCGeomMultiLine" ],
    [ "CGeomProfile", "da/dae/classCGeomProfile.html", "da/dae/classCGeomProfile" ],
    [ "CGeomRasterGrid", "d6/d3e/classCGeomRasterGrid.html", "d6/d3e/classCGeomRasterGrid" ],
    [ "CRWCellLandform", "dc/d4a/classCRWCellLandform.html", "dc/d4a/classCRWCellLandform" ],
    [ "CRWCellLayer", "d5/d6d/classCRWCellLayer.html", "d5/d6d/classCRWCellLayer" ],
    [ "CRWCellSediment", "d5/dc6/classCRWCellSediment.html", "d5/dc6/classCRWCellSediment" ],
    [ "CRWCellTalus", "da/ddf/classCRWCellTalus.html", "da/ddf/classCRWCellTalus" ],
    [ "CRWCliff", "d9/d8b/classCRWCliff.html", "d9/d8b/classCRWCliff" ],
    [ "CRWCoast", "d1/dbe/classCRWCoast.html", "d1/dbe/classCRWCoast" ],
    [ "CRWDrift", "d0/d02/classCRWDrift.html", "d0/d02/classCRWDrift" ],
    [ "CRWIntervention", "d4/d51/classCRWIntervention.html", "d4/d51/classCRWIntervention" ],
    [ "CRWSedInputEvent", "d4/d9d/classCRWSedInputEvent.html", "d4/d9d/classCRWSedInputEvent" ],
    [ "CSimulation", "d1/d98/classCSimulation.html", "d1/d98/classCSimulation" ],
    [ "CYamlNode", "d7/dab/classCYamlNode.html", "d7/dab/classCYamlNode" ],
    [ "CYamlParser", "d1/dd6/classCYamlParser.html", "d1/dd6/classCYamlParser" ],
    [ "deque", "dd/d58/classdeque.html", "dd/d58/classdeque" ],
    [ "DualSpatialInterpolator", "db/d00/classDualSpatialInterpolator.html", "db/d00/classDualSpatialInterpolator" ],
    [ "GDALDataType", "d9/da5/classGDALDataType.html", null ],
    [ "ifstream", "d0/d68/classifstream.html", null ],
    [ "ios", "df/d02/classios.html", null ],
    [ "istringstream", "dc/d35/classistringstream.html", null ],
    [ "map", "d9/d28/classmap.html", "d9/d28/classmap" ],
    [ "ofstream", "d9/d93/classofstream.html", null ],
    [ "ostream", "d0/d43/classostream.html", null ],
    [ "ostringstream", "d8/d79/classostringstream.html", null ],
    [ "pair", "d2/d11/classpair.html", "d2/d11/classpair" ],
    [ "Point2D", "d2/d6b/structPoint2D.html", "d2/d6b/structPoint2D" ],
    [ "PointCloud", "dd/d9f/structPointCloud.html", "dd/d9f/structPointCloud" ],
    [ "set", "d0/d59/classset.html", "d0/d59/classset" ],
    [ "SpatialInterpolator", "d4/da8/classSpatialInterpolator.html", "d4/da8/classSpatialInterpolator" ],
    [ "stack", "d1/dc2/classstack.html", "d1/dc2/classstack" ],
    [ "string", "d5/d92/classstring.html", "d5/d92/classstring" ],
    [ "stringstream", "d9/d61/classstringstream.html", null ],
    [ "UnstableCell", "d1/d5e/structUnstableCell.html", "d1/d5e/structUnstableCell" ],
    [ "UnstableCellComparator", "dd/d86/structUnstableCellComparator.html", "dd/d86/structUnstableCellComparator" ],
    [ "vector", "d7/dfc/classvector.html", "d7/dfc/classvector" ]
];