CoastalME (Coastal Modelling Environment): hermite_cubic.h File Reference
hermite_cubic.h File Reference
Definitions of some routines from the hermite_cubic library.
Functions
void r8vec_bracket3 (int const, double const *, double const, int *)
This is part of a C++ library from http://people.sc.fsu.edu/~jburkardt/cpp_src/hermite_cubic/hermite_cubic.html. It demonstrates the use of cubic polynomials in the Hermite form: r8vec_bracket3() finds the interval containing or nearest to a given value.
void hermite_cubic_value (double const, double const, double const, double const, double const, double const, int const, double const *, double *const, double *const, double *const, double *const)
This is part of a C++ library from http://people.sc.fsu.edu/~jburkardt/cpp_src/hermite_cubic/hermite_cubic.html. It demonstrates the use of cubic polynomials in the Hermite form: hermite_cubic_spline_value() evaluates a Hermite cubic spline//===============================================================================================================================.
void hermite_cubic_spline_value (int const, double *const, double *const, double *const, int const, double *const, double *, double *, double *, double *)
This is part of a C++ library from http://people.sc.fsu.edu/~jburkardt/cpp_src/hermite_cubic/hermite_cubic.html. It demonstrates the use of cubic polynomials in the Hermite form: hermite_cubic_value() evaluates a Hermite cubic polynomial. Here, it is used in the calculation of erosion potetial for shore platform erosion.
Detailed Description
Definitions of some routines from the hermite_cubic library.
TODO 001 This is a more detailed description of the hermite_cubic routines.
Author
John Burkardt
Modified by David Favis-Mortlock and Andres Payo
Date
2025
Copyright
GNU Lesser General Public License *
Contains definitions of hermite-cubic routines
Definition in file hermite_cubic.h.
Function Documentation
hermite_cubic_spline_value()
void hermite_cubic_spline_value (int const nn, double * const xn, double * const fn, double * const dn, int const n, double * const x, double * f, double * d, double * s, double * t)
This is part of a C++ library from http://people.sc.fsu.edu/~jburkardt/cpp_src/hermite_cubic/hermite_cubic.html. It demonstrates the use of cubic polynomials in the Hermite form: hermite_cubic_value() evaluates a Hermite cubic polynomial. Here, it is used in the calculation of erosion potetial for shore platform erosion.
Definition at line 343 of file hermite_cubic.cpp.
Referenced by CSimulation::bCreateErosionPotentialLookUp().
hermite_cubic_value()
void hermite_cubic_value (double const x1, double const f1, double const d1, double const x2, double const f2, double const d2, int const n, double const * x, double * const f, double * const d, double * const s, double * const t)
This is part of a C++ library from http://people.sc.fsu.edu/~jburkardt/cpp_src/hermite_cubic/hermite_cubic.html. It demonstrates the use of cubic polynomials in the Hermite form: hermite_cubic_spline_value() evaluates a Hermite cubic spline//===============================================================================================================================.
Definition at line 263 of file hermite_cubic.cpp.
Referenced by hermite_cubic_spline_value().
r8vec_bracket3()
void r8vec_bracket3 (int const n, double const * t, double const tval, int * left)
This is part of a C++ library from http://people.sc.fsu.edu/~jburkardt/cpp_src/hermite_cubic/hermite_cubic.html. It demonstrates the use of cubic polynomials in the Hermite form: r8vec_bracket3() finds the interval containing or nearest to a given value.
Definition at line 90 of file hermite_cubic.cpp.
Referenced by hermite_cubic_spline_value().