CoastalME (Coastal Modelling Environment): CCliffAlgorithmFactory Class Reference
CCliffAlgorithmFactory Class Reference
Factory class for creating cliff collapse algorithms.
#include <cliff_algorithm_factory.h>
Static Public Member Functions
static unique_ptr< CCliffAlgorithm > CreateAlgorithm (const string &strAlgorithmName)
Create a cliff algorithm instance by name.
static unique_ptr< CCliffAlgorithm > CreateAlgorithm (ECliffAlgorithm algorithmType)
Create a cliff algorithm instance by enum.
static vector< string > GetAvailableAlgorithms ()
Get list of available algorithm names.
static bool IsValidAlgorithm (const string &strAlgorithmName)
Check if algorithm name is valid.
static ECliffAlgorithm GetAlgorithmEnum (const string &strAlgorithmName)
Convert algorithm name to enum.
static string GetAlgorithmName (ECliffAlgorithm algorithmType)
Convert enum to algorithm name.
Detailed Description
Factory class for creating cliff collapse algorithms.
This class provides a factory pattern for creating different cliff collapse algorithms
Author
Wilf Chun
Date
2025
Copyright
GNU General Public License
Definition at line 45 of file cliff_algorithm_factory.h.
Member Function Documentation
CreateAlgorithm() [1/2]
unique_ptr< CCliffAlgorithm > CCliffAlgorithmFactory::CreateAlgorithm (const string & strAlgorithmName) static
Create a cliff algorithm instance by name.
Definition at line 38 of file cliff_algorithm_factory.cpp.
Referenced by CreateAlgorithm(), CCliffCollapseManager::Initialize(), and CCliffCollapseManager::SwitchAlgorithm().
CreateAlgorithm() [2/2]
unique_ptr< CCliffAlgorithm > CCliffAlgorithmFactory::CreateAlgorithm (ECliffAlgorithm algorithmType) static
Create a cliff algorithm instance by enum.
Definition at line 44 of file cliff_algorithm_factory.cpp.
GetAlgorithmEnum()
ECliffAlgorithm CCliffAlgorithmFactory::GetAlgorithmEnum (const string & strAlgorithmName) static
Convert algorithm name to enum.
Definition at line 82 of file cliff_algorithm_factory.cpp.
Referenced by CreateAlgorithm().
GetAlgorithmName()
string CCliffAlgorithmFactory::GetAlgorithmName (ECliffAlgorithm algorithmType) static
Convert enum to algorithm name.
Definition at line 96 of file cliff_algorithm_factory.cpp.
GetAvailableAlgorithms()
vector< string > CCliffAlgorithmFactory::GetAvailableAlgorithms () static
Get list of available algorithm names.
Definition at line 61 of file cliff_algorithm_factory.cpp.
Referenced by CSimulation::bReadRunDataFile(), CCliffCollapseManager::GetAvailableAlgorithms(), and IsValidAlgorithm().
IsValidAlgorithm()
bool CCliffAlgorithmFactory::IsValidAlgorithm (const string & strAlgorithmName) static
Check if algorithm name is valid.
Definition at line 67 of file cliff_algorithm_factory.cpp.
Referenced by CSimulation::bReadRunDataFile().
The documentation for this class was generated from the following files:
cliff_algorithm_factory.h
cliff_algorithm_factory.cpp