CoastalME (Coastal Modelling Environment): CConfiguration Class Reference
CConfiguration Class Reference
Unified configuration class for CoastalME simulation parameters.
#include <configuration.h>
Public Member Functions
CConfiguration ()
Constructor.
~CConfiguration ()
Destructor.
void SetRunName (string const &str)
void SetLogFileDetail (int n)
void SetCSVPerTimestepResults (bool b)
void SetStartDateTime (string const &str)
void SetDuration (string const &str)
void SetTimestep (string const &str)
void SetSaveTimes (vector< string > const &vec)
void SetRandomSeed (int n)
void UseSystemTimeForSeed ()
void SetMaxSaveDigits (int n)
void SetSaveDigitsMode (string const &str)
void SetRasterFiles (vector< string > const &vec)
void SetRasterFormat (string const &str)
void SetWorldFile (bool b)
void SetScaleValues (bool b)
void SetSliceElevations (vector< double > const &vec)
void SetVectorFiles (vector< string > const &vec)
void SetVectorFormat (string const &str)
void SetTimeSeriesFiles (vector< string > const &vec)
void SetCoastlineSmoothing (int n)
void SetCoastlineSmoothingWindow (int n)
void SetPolynomialOrder (int n)
void SetOmitGridEdges (string const &str)
void SetProfileSmoothingWindow (int n)
void SetMaxLocalSlope (double d)
void SetMaxBeachElevation (double d)
void SetNumLayers (int n)
void SetBasementDEMFile (string const &str)
void SetUnconsFineFiles (vector< string > const &vec)
void SetUnconsSandFiles (vector< string > const &vec)
void SetUnconsCoarseFiles (vector< string > const &vec)
void SetConsFineFiles (vector< string > const &vec)
void SetConsSandFiles (vector< string > const &vec)
void SetConsCoarseFiles (vector< string > const &vec)
void SetSuspendedSedFile (string const &str)
void SetLandformFile (string const &str)
void SetInterventionClassFile (string const &str)
void SetInterventionHeightFile (string const &str)
void SetWavePropagationModel (int n)
void SetSeawaterDensity (double d)
void SetInitialWaterLevel (double d)
void SetFinalWaterLevel (double d)
void SetWaveHeightTimeSeries (string const &str)
void SetWaveStationDataFile (string const &str)
void SetDeepWaterWaveHeight (double d)
void SetDeepWaterWaveOrientation (double d)
void SetWavePeriod (double d)
void SetTideDataFile (string const &str)
void SetBreakingWaveRatio (double d)
void SetCoastPlatformErosion (bool b)
void SetPlatformErosionResistance (double d)
void SetBeachSedimentTransport (bool b)
void SetBeachTransportAtEdges (int n)
void SetBeachErosionEquation (int n)
void SetFineMedianSize (double d)
void SetSandMedianSize (double d)
void SetCoarseMedianSize (double d)
void SetSedimentDensity (double d)
void SetBeachSedimentPorosity (double d)
void SetFineErosivity (double d)
void SetSandErosivity (double d)
void SetCoarseErosivity (double d)
void SetTransportKLS (double d)
void SetKamphuis (double d)
void SetBermHeight (double d)
void SetCliffCollapse (bool b)
void SetCliffErosionResistance (double d)
void SetNotchOverhang (double d)
void SetNotchBase (double d)
void SetCliffDepositionA (double d)
void SetTalusWidth (double d)
void SetMinTalusLength (double d)
void SetMinTalusHeight (double d)
void SetFloodInput (bool b)
void SetFloodFiles (vector< string > v)
void SetFloodCoastline (string const &str)
void SetRunupEquation (string const &str)
void SetFloodLocations (string const &str)
void SetFloodInputLocation (string const &str)
void SetSedimentInput (bool b)
void SetSedimentInputLocation (string const &str)
void SetSedimentInputType (string const &str)
void SetSedimentInputDetails (string const &str)
void SetGravitationalAcceleration (double d)
void SetNormalSpacing (double d)
void SetRandomFactor (double d)
void SetNormalLength (double d)
void SetStartDepthRatio (double d)
void SetSaveProfileData (bool b)
void SetProfileNumbers (vector< int > const &vec)
void SetProfileTimesteps (vector< unsigned long > const &vec)
void SetSaveParallelProfiles (bool b)
void SetOutputErosionPotential (bool b)
void SetCurvatureWindow (int n)
void SetCliffEdgeSmoothing (int n)
void SetCliffEdgeSmoothingWindow (int n)
void SetCliffEdgePolynomialOrder (int n)
void SetCliffSlopeLimit (double d)
string GetRunName () const
int GetLogFileDetail () const
bool GetCSVPerTimestepResults () const
string GetStartDateTime () const
string GetDuration () const
string GetTimestep () const
vector< string > GetSaveTimes () const
int GetRandomSeed () const
bool UseSystemTimeForRandomSeed () const
int GetMaxSaveDigits () const
string GetSaveDigitsMode () const
vector< string > GetRasterFiles () const
Get raster files with keyword expansion support.
string GetRasterFormat () const
bool GetWorldFile () const
bool GetScaleValues () const
vector< double > GetSliceElevations () const
vector< string > GetVectorFiles () const
Get vector files with keyword expansion support.
string GetVectorFormat () const
vector< string > GetTimeSeriesFiles () const
Get time series files with keyword expansion support.
int GetCoastlineSmoothing () const
int GetCoastlineSmoothingWindow () const
int GetPolynomialOrder () const
string GetOmitGridEdges () const
int GetProfileSmoothingWindow () const
double GetMaxLocalSlope () const
double GetMaxBeachElevation () const
int GetNumLayers () const
string GetBasementDEMFile () const
vector< string > GetUnconsFineFiles () const
vector< string > GetUnconsSandFiles () const
vector< string > GetUnconsCoarseFiles () const
vector< string > GetConsFineFiles () const
vector< string > GetConsSandFiles () const
vector< string > GetConsCoarseFiles () const
string GetSuspendedSedFile () const
string GetLandformFile () const
string GetInterventionClassFile () const
string GetInterventionHeightFile () const
int GetWavePropagationModel () const
double GetSeawaterDensity () const
double GetInitialWaterLevel () const
double GetFinalWaterLevel () const
bool HasFinalWaterLevel () const
string GetWaveHeightTimeSeries () const
string GetWaveStationDataFile () const
double GetDeepWaterWaveHeight () const
double GetDeepWaterWaveOrientation () const
double GetWavePeriod () const
string GetTideDataFile () const
double GetBreakingWaveRatio () const
bool GetCoastPlatformErosion () const
double GetPlatformErosionResistance () const
bool GetBeachSedimentTransport () const
int GetBeachTransportAtEdges () const
int GetBeachErosionEquation () const
double GetFineMedianSize () const
double GetSandMedianSize () const
double GetCoarseMedianSize () const
double GetSedimentDensity () const
double GetBeachSedimentPorosity () const
double GetFineErosivity () const
double GetSandErosivity () const
double GetCoarseErosivity () const
double GetTransportKLS () const
double GetKamphuis () const
double GetBermHeight () const
bool GetCliffCollapse () const
double GetCliffErosionResistance () const
double GetNotchOverhang () const
double GetNotchBase () const
double GetCliffDepositionA () const
double GetTalusWidth () const
double GetMinTalusLength () const
double GetMinTalusHeight () const
bool GetFloodInput () const
vector< string > GetFloodFiles () const
Get time series files with keyword expansion support.
string GetFloodCoastline () const
int GetRunupEquation () const
string GetFloodLocations () const
string GetFloodInputLocation () const
bool GetSedimentInput () const
string GetSedimentInputLocation () const
string GetSedimentInputType () const
string GetSedimentInputDetails () const
double GetGravitationalAcceleration () const
double GetNormalSpacing () const
double GetRandomFactor () const
double GetNormalLength () const
double GetStartDepthRatio () const
bool GetSaveProfileData () const
vector< int > GetProfileNumbers () const
vector< unsigned long > GetProfileTimesteps () const
bool GetSaveParallelProfiles () const
bool GetOutputErosionPotential () const
int GetCurvatureWindow () const
int GetCliffEdgeSmoothing () const
int GetCliffEdgeSmoothingWindow () const
int GetCliffEdgePolynomialOrder () const
double GetCliffSlopeLimit () const
void InitializeDefaults ()
Initialize all parameters with default values.
Private Attributes
string m_strRunName
int m_nLogFileDetail
bool m_bCSVPerTimestepResults
string m_strStartDateTime
string m_strDuration
string m_strTimestep
vector< string > m_vecSaveTimes
int m_nRandomSeed
bool m_bUseSystemTimeForSeed
int m_nMaxSaveDigits
string m_strSaveDigitsMode
vector< string > m_vecRasterFiles
string m_strRasterFormat
bool m_bWorldFile
bool m_bScaleValues
vector< double > m_vecSliceElevations
vector< string > m_vecVectorFiles
string m_strVectorFormat
vector< string > m_vecTimeSeriesFiles
int m_nCoastlineSmoothing
int m_nCoastlineSmoothingWindow
int m_nPolynomialOrder
string m_strOmitGridEdges
int m_nProfileSmoothingWindow
double m_dMaxLocalSlope
double m_dMaxBeachElevation
int m_nNumLayers
string m_strBasementDEMFile
vector< string > m_vecUnconsFineFiles
vector< string > m_vecUnconsSandFiles
vector< string > m_vecUnconsCoarseFiles
vector< string > m_vecConsFineFiles
vector< string > m_vecConsSandFiles
vector< string > m_vecConsCoarseFiles
string m_strSuspendedSedFile
string m_strLandformFile
string m_strInterventionClassFile
string m_strInterventionHeightFile
int m_nWavePropagationModel
double m_dSeawaterDensity
double m_dInitialWaterLevel
double m_dFinalWaterLevel
bool m_bHasFinalWaterLevel
string m_strWaveHeightTimeSeries
string m_strWaveStationDataFile
double m_dDeepWaterWaveHeight
double m_dDeepWaterWaveOrientation
double m_dWavePeriod
string m_strTideDataFile
double m_dBreakingWaveRatio
bool m_bCoastPlatformErosion
double m_dPlatformErosionResistance
bool m_bBeachSedimentTransport
int m_nBeachTransportAtEdges
int m_nBeachErosionEquation
double m_dFineMedianSize
double m_dSandMedianSize
double m_dCoarseMedianSize
double m_dSedimentDensity
double m_dBeachSedimentPorosity
double m_dFineErosivity
double m_dSandErosivity
double m_dCoarseErosivity
double m_dTransportKLS
double m_dKamphuis
double m_dBermHeight
bool m_bCliffCollapse
double m_dCliffErosionResistance
double m_dNotchOverhang
double m_dNotchBase
double m_dCliffDepositionA
double m_dTalusWidth
double m_dMinTalusLength
double m_dMinTalusHeight
bool m_bFloodInput
string m_strFloodCoastline
int m_strRunupEquation
string m_strFloodLocations
string m_strFloodInputLocation
vector< string > m_vecFloodFiles
bool m_bSedimentInput
string m_strSedimentInputLocation
string m_strSedimentInputType
string m_strSedimentInputDetails
double m_dGravitationalAcceleration
double m_dNormalSpacing
double m_dRandomFactor
double m_dNormalLength
double m_dStartDepthRatio
bool m_bSaveProfileData
vector< int > m_vecProfileNumbers
vector< unsigned long > m_vecProfileTimesteps
bool m_bSaveParallelProfiles
bool m_bOutputErosionPotential
int m_nCurvatureWindow
int m_nCliffEdgeSmoothing
int m_nCliffEdgeSmoothingWindow
int m_nCliffEdgePolynomialOrder
double m_dCliffSlopeLimit
Detailed Description
Unified configuration class for CoastalME simulation parameters.
Definition at line 44 of file configuration.h.
Constructor & Destructor Documentation
CConfiguration()
CConfiguration::CConfiguration ()
Constructor.
Definition at line 34 of file configuration.cpp.
~CConfiguration()
CConfiguration::~CConfiguration ()
Destructor.
Definition at line 42 of file configuration.cpp.
Member Function Documentation
GetBasementDEMFile()
string CConfiguration::GetBasementDEMFile () const inline
Definition at line 697 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetBeachErosionEquation()
int CConfiguration::GetBeachErosionEquation () const inline
Definition at line 811 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetBeachSedimentPorosity()
double CConfiguration::GetBeachSedimentPorosity () const inline
Definition at line 831 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetBeachSedimentTransport()
bool CConfiguration::GetBeachSedimentTransport () const inline
Definition at line 803 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetBeachTransportAtEdges()
int CConfiguration::GetBeachTransportAtEdges () const inline
Definition at line 807 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetBermHeight()
double CConfiguration::GetBermHeight () const inline
Definition at line 855 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetBreakingWaveRatio()
double CConfiguration::GetBreakingWaveRatio () const inline
Definition at line 789 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCliffCollapse()
bool CConfiguration::GetCliffCollapse () const inline
Definition at line 861 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCliffDepositionA()
double CConfiguration::GetCliffDepositionA () const inline
Definition at line 877 of file configuration.h.
GetCliffEdgePolynomialOrder()
int CConfiguration::GetCliffEdgePolynomialOrder () const inline
Definition at line 993 of file configuration.h.
GetCliffEdgeSmoothing()
int CConfiguration::GetCliffEdgeSmoothing () const inline
Definition at line 985 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCliffEdgeSmoothingWindow()
int CConfiguration::GetCliffEdgeSmoothingWindow () const inline
Definition at line 989 of file configuration.h.
GetCliffErosionResistance()
double CConfiguration::GetCliffErosionResistance () const inline
Definition at line 865 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCliffSlopeLimit()
double CConfiguration::GetCliffSlopeLimit () const inline
Definition at line 997 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCoarseErosivity()
double CConfiguration::GetCoarseErosivity () const inline
Definition at line 843 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCoarseMedianSize()
double CConfiguration::GetCoarseMedianSize () const inline
Definition at line 823 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCoastlineSmoothing()
int CConfiguration::GetCoastlineSmoothing () const inline
Definition at line 667 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCoastlineSmoothingWindow()
int CConfiguration::GetCoastlineSmoothingWindow () const inline
Definition at line 671 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCoastPlatformErosion()
bool CConfiguration::GetCoastPlatformErosion () const inline
Definition at line 795 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetConsCoarseFiles()
vector< string > CConfiguration::GetConsCoarseFiles () const inline
Definition at line 721 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetConsFineFiles()
vector< string > CConfiguration::GetConsFineFiles () const inline
Definition at line 713 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetConsSandFiles()
vector< string > CConfiguration::GetConsSandFiles () const inline
Definition at line 717 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCSVPerTimestepResults()
bool CConfiguration::GetCSVPerTimestepResults () const inline
Definition at line 606 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetCurvatureWindow()
int CConfiguration::GetCurvatureWindow () const inline
Definition at line 979 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetDeepWaterWaveHeight()
double CConfiguration::GetDeepWaterWaveHeight () const inline
Definition at line 772 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetDeepWaterWaveOrientation()
double CConfiguration::GetDeepWaterWaveOrientation () const inline
Definition at line 776 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetDuration()
string CConfiguration::GetDuration () const inline
Definition at line 614 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetFinalWaterLevel()
double CConfiguration::GetFinalWaterLevel () const inline
Definition at line 754 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetFineErosivity()
double CConfiguration::GetFineErosivity () const inline
Definition at line 835 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetFineMedianSize()
double CConfiguration::GetFineMedianSize () const inline
Definition at line 815 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetFloodCoastline()
string CConfiguration::GetFloodCoastline () const inline
Definition at line 901 of file configuration.h.
GetFloodFiles()
vector< string > CConfiguration::GetFloodFiles () const
Get time series files with keyword expansion support.
Definition at line 421 of file configuration.cpp.
Referenced by CSimulation::bApplyConfiguration().
GetFloodInput()
bool CConfiguration::GetFloodInput () const inline
Definition at line 895 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetFloodInputLocation()
string CConfiguration::GetFloodInputLocation () const inline
Definition at line 913 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetFloodLocations()
string CConfiguration::GetFloodLocations () const inline
Definition at line 909 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetGravitationalAcceleration()
double CConfiguration::GetGravitationalAcceleration () const inline
Definition at line 937 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetInitialWaterLevel()
double CConfiguration::GetInitialWaterLevel () const inline
Definition at line 750 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetInterventionClassFile()
string CConfiguration::GetInterventionClassFile () const inline
Definition at line 733 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetInterventionHeightFile()
string CConfiguration::GetInterventionHeightFile () const inline
Definition at line 737 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetKamphuis()
double CConfiguration::GetKamphuis () const inline
Definition at line 851 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetLandformFile()
string CConfiguration::GetLandformFile () const inline
Definition at line 729 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetLogFileDetail()
int CConfiguration::GetLogFileDetail () const inline
Definition at line 602 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetMaxBeachElevation()
double CConfiguration::GetMaxBeachElevation () const inline
Definition at line 688 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetMaxLocalSlope()
double CConfiguration::GetMaxLocalSlope () const inline
Definition at line 684 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetMaxSaveDigits()
int CConfiguration::GetMaxSaveDigits () const inline
Definition at line 635 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetMinTalusHeight()
double CConfiguration::GetMinTalusHeight () const inline
Definition at line 889 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetMinTalusLength()
double CConfiguration::GetMinTalusLength () const inline
Definition at line 885 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetNormalLength()
double CConfiguration::GetNormalLength () const inline
Definition at line 949 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetNormalSpacing()
double CConfiguration::GetNormalSpacing () const inline
Definition at line 941 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetNotchBase()
double CConfiguration::GetNotchBase () const inline
Definition at line 873 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetNotchOverhang()
double CConfiguration::GetNotchOverhang () const inline
Definition at line 869 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetNumLayers()
int CConfiguration::GetNumLayers () const inline
Definition at line 693 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetOmitGridEdges()
string CConfiguration::GetOmitGridEdges () const
Definition at line 451 of file configuration.cpp.
Referenced by CSimulation::bApplyConfiguration().
GetOutputErosionPotential()
bool CConfiguration::GetOutputErosionPotential () const inline
Definition at line 975 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetPlatformErosionResistance()
double CConfiguration::GetPlatformErosionResistance () const inline
Definition at line 799 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetPolynomialOrder()
int CConfiguration::GetPolynomialOrder () const inline
Definition at line 675 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetProfileNumbers()
vector< int > CConfiguration::GetProfileNumbers () const inline
Definition at line 963 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetProfileSmoothingWindow()
int CConfiguration::GetProfileSmoothingWindow () const inline
Definition at line 680 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetProfileTimesteps()
vector< unsigned long > CConfiguration::GetProfileTimesteps () const inline
Definition at line 967 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetRandomFactor()
double CConfiguration::GetRandomFactor () const inline
Definition at line 945 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetRandomSeed()
int CConfiguration::GetRandomSeed () const inline
Definition at line 626 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetRasterFiles()
vector< string > CConfiguration::GetRasterFiles () const
Get raster files with keyword expansion support.
Definition at line 184 of file configuration.cpp.
Referenced by CSimulation::bApplyConfiguration().
GetRasterFormat()
string CConfiguration::GetRasterFormat () const inline
Definition at line 644 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetRunName()
string CConfiguration::GetRunName () const inline
Definition at line 598 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetRunupEquation()
int CConfiguration::GetRunupEquation () const inline
Definition at line 905 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSandErosivity()
double CConfiguration::GetSandErosivity () const inline
Definition at line 839 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSandMedianSize()
double CConfiguration::GetSandMedianSize () const inline
Definition at line 819 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSaveDigitsMode()
string CConfiguration::GetSaveDigitsMode () const inline
Definition at line 639 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSaveParallelProfiles()
bool CConfiguration::GetSaveParallelProfiles () const inline
Definition at line 971 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSaveProfileData()
bool CConfiguration::GetSaveProfileData () const inline
Definition at line 959 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSaveTimes()
vector< string > CConfiguration::GetSaveTimes () const inline
Definition at line 622 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetScaleValues()
bool CConfiguration::GetScaleValues () const inline
Definition at line 652 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSeawaterDensity()
double CConfiguration::GetSeawaterDensity () const inline
Definition at line 746 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSedimentDensity()
double CConfiguration::GetSedimentDensity () const inline
Definition at line 827 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSedimentInput()
bool CConfiguration::GetSedimentInput () const inline
Definition at line 919 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSedimentInputDetails()
string CConfiguration::GetSedimentInputDetails () const inline
Definition at line 931 of file configuration.h.
GetSedimentInputLocation()
string CConfiguration::GetSedimentInputLocation () const inline
Definition at line 923 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSedimentInputType()
string CConfiguration::GetSedimentInputType () const inline
Definition at line 927 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetSliceElevations()
vector< double > CConfiguration::GetSliceElevations () const inline
Definition at line 656 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetStartDateTime()
string CConfiguration::GetStartDateTime () const inline
Definition at line 610 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetStartDepthRatio()
double CConfiguration::GetStartDepthRatio () const inline
Definition at line 953 of file configuration.h.
GetSuspendedSedFile()
string CConfiguration::GetSuspendedSedFile () const inline
Definition at line 725 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetTalusWidth()
double CConfiguration::GetTalusWidth () const inline
Definition at line 881 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetTideDataFile()
string CConfiguration::GetTideDataFile () const inline
Definition at line 785 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetTimeSeriesFiles()
vector< string > CConfiguration::GetTimeSeriesFiles () const
Get time series files with keyword expansion support.
Definition at line 389 of file configuration.cpp.
Referenced by CSimulation::bApplyConfiguration().
GetTimestep()
string CConfiguration::GetTimestep () const inline
Definition at line 618 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetTransportKLS()
double CConfiguration::GetTransportKLS () const inline
Definition at line 847 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetUnconsCoarseFiles()
vector< string > CConfiguration::GetUnconsCoarseFiles () const inline
Definition at line 709 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetUnconsFineFiles()
vector< string > CConfiguration::GetUnconsFineFiles () const inline
Definition at line 701 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetUnconsSandFiles()
vector< string > CConfiguration::GetUnconsSandFiles () const inline
Definition at line 705 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetVectorFiles()
vector< string > CConfiguration::GetVectorFiles () const
Get vector files with keyword expansion support.
Definition at line 346 of file configuration.cpp.
Referenced by CSimulation::bApplyConfiguration().
GetVectorFormat()
string CConfiguration::GetVectorFormat () const inline
Definition at line 661 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetWaveHeightTimeSeries()
string CConfiguration::GetWaveHeightTimeSeries () const inline
Definition at line 764 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetWavePeriod()
double CConfiguration::GetWavePeriod () const inline
Definition at line 780 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetWavePropagationModel()
int CConfiguration::GetWavePropagationModel () const inline
Definition at line 742 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetWaveStationDataFile()
string CConfiguration::GetWaveStationDataFile () const inline
Definition at line 768 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
GetWorldFile()
bool CConfiguration::GetWorldFile () const inline
Definition at line 648 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
HasFinalWaterLevel()
bool CConfiguration::HasFinalWaterLevel () const inline
Definition at line 758 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
InitializeDefaults()
void CConfiguration::InitializeDefaults ()
Initialize all parameters with default values.
Definition at line 49 of file configuration.cpp.
Referenced by CConfiguration().
SetBasementDEMFile()
void CConfiguration::SetBasementDEMFile (string const & str) inline
Definition at line 292 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetBeachErosionEquation()
void CConfiguration::SetBeachErosionEquation (int n) inline
Definition at line 403 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetBeachSedimentPorosity()
void CConfiguration::SetBeachSedimentPorosity (double d) inline
Definition at line 423 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetBeachSedimentTransport()
void CConfiguration::SetBeachSedimentTransport (bool b) inline
Definition at line 395 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetBeachTransportAtEdges()
void CConfiguration::SetBeachTransportAtEdges (int n) inline
Definition at line 399 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetBermHeight()
void CConfiguration::SetBermHeight (double d) inline
Definition at line 447 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetBreakingWaveRatio()
void CConfiguration::SetBreakingWaveRatio (double d) inline
Definition at line 381 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCliffCollapse()
void CConfiguration::SetCliffCollapse (bool b) inline
Definition at line 452 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCliffDepositionA()
void CConfiguration::SetCliffDepositionA (double d) inline
Definition at line 468 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCliffEdgePolynomialOrder()
void CConfiguration::SetCliffEdgePolynomialOrder (int n) inline
Definition at line 588 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCliffEdgeSmoothing()
void CConfiguration::SetCliffEdgeSmoothing (int n) inline
Definition at line 580 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCliffEdgeSmoothingWindow()
void CConfiguration::SetCliffEdgeSmoothingWindow (int n) inline
Definition at line 584 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCliffErosionResistance()
void CConfiguration::SetCliffErosionResistance (double d) inline
Definition at line 456 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCliffSlopeLimit()
void CConfiguration::SetCliffSlopeLimit (double d) inline
Definition at line 592 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCoarseErosivity()
void CConfiguration::SetCoarseErosivity (double d) inline
Definition at line 435 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCoarseMedianSize()
void CConfiguration::SetCoarseMedianSize (double d) inline
Definition at line 415 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCoastlineSmoothing()
void CConfiguration::SetCoastlineSmoothing (int n) inline
Definition at line 260 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCoastlineSmoothingWindow()
void CConfiguration::SetCoastlineSmoothingWindow (int n) inline
Definition at line 264 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCoastPlatformErosion()
void CConfiguration::SetCoastPlatformErosion (bool b) inline
Definition at line 387 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetConsCoarseFiles()
void CConfiguration::SetConsCoarseFiles (vector< string > const & vec) inline
Definition at line 316 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetConsFineFiles()
void CConfiguration::SetConsFineFiles (vector< string > const & vec) inline
Definition at line 308 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetConsSandFiles()
void CConfiguration::SetConsSandFiles (vector< string > const & vec) inline
Definition at line 312 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCSVPerTimestepResults()
void CConfiguration::SetCSVPerTimestepResults (bool b) inline
Definition at line 189 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetCurvatureWindow()
void CConfiguration::SetCurvatureWindow (int n) inline
Definition at line 575 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetDeepWaterWaveHeight()
void CConfiguration::SetDeepWaterWaveHeight (double d) inline
Definition at line 364 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetDeepWaterWaveOrientation()
void CConfiguration::SetDeepWaterWaveOrientation (double d) inline
Definition at line 368 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetDuration()
void CConfiguration::SetDuration (string const & str) inline
Definition at line 197 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetFinalWaterLevel()
void CConfiguration::SetFinalWaterLevel (double d) inline
Definition at line 349 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetFineErosivity()
void CConfiguration::SetFineErosivity (double d) inline
Definition at line 427 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetFineMedianSize()
void CConfiguration::SetFineMedianSize (double d) inline
Definition at line 407 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetFloodCoastline()
void CConfiguration::SetFloodCoastline (string const & str) inline
Definition at line 493 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetFloodFiles()
void CConfiguration::SetFloodFiles (vector< string > v) inline
Definition at line 489 of file configuration.h.
SetFloodInput()
void CConfiguration::SetFloodInput (bool b) inline
Definition at line 485 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetFloodInputLocation()
void CConfiguration::SetFloodInputLocation (string const & str) inline
Definition at line 512 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetFloodLocations()
void CConfiguration::SetFloodLocations (string const & str) inline
Definition at line 508 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetGravitationalAcceleration()
void CConfiguration::SetGravitationalAcceleration (double d) inline
Definition at line 534 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetInitialWaterLevel()
void CConfiguration::SetInitialWaterLevel (double d) inline
Definition at line 345 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetInterventionClassFile()
void CConfiguration::SetInterventionClassFile (string const & str) inline
Definition at line 328 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetInterventionHeightFile()
void CConfiguration::SetInterventionHeightFile (string const & str) inline
Definition at line 332 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetKamphuis()
void CConfiguration::SetKamphuis (double d) inline
Definition at line 443 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetLandformFile()
void CConfiguration::SetLandformFile (string const & str) inline
Definition at line 324 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetLogFileDetail()
void CConfiguration::SetLogFileDetail (int n) inline
Definition at line 185 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetMaxBeachElevation()
void CConfiguration::SetMaxBeachElevation (double d) inline
Definition at line 284 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetMaxLocalSlope()
void CConfiguration::SetMaxLocalSlope (double d) inline
Definition at line 280 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetMaxSaveDigits()
void CConfiguration::SetMaxSaveDigits (int n) inline
Definition at line 219 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetMinTalusHeight()
void CConfiguration::SetMinTalusHeight (double d) inline
Definition at line 480 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetMinTalusLength()
void CConfiguration::SetMinTalusLength (double d) inline
Definition at line 476 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetNormalLength()
void CConfiguration::SetNormalLength (double d) inline
Definition at line 546 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetNormalSpacing()
void CConfiguration::SetNormalSpacing (double d) inline
Definition at line 538 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetNotchBase()
void CConfiguration::SetNotchBase (double d) inline
Definition at line 464 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetNotchOverhang()
void CConfiguration::SetNotchOverhang (double d) inline
Definition at line 460 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetNumLayers()
void CConfiguration::SetNumLayers (int n) inline
Definition at line 288 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetOmitGridEdges()
void CConfiguration::SetOmitGridEdges (string const & str) inline
Definition at line 272 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetOutputErosionPotential()
void CConfiguration::SetOutputErosionPotential (bool b) inline
Definition at line 571 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetPlatformErosionResistance()
void CConfiguration::SetPlatformErosionResistance (double d) inline
Definition at line 391 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetPolynomialOrder()
void CConfiguration::SetPolynomialOrder (int n) inline
Definition at line 268 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetProfileNumbers()
void CConfiguration::SetProfileNumbers (vector< int > const & vec) inline
Definition at line 559 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetProfileSmoothingWindow()
void CConfiguration::SetProfileSmoothingWindow (int n) inline
Definition at line 276 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetProfileTimesteps()
void CConfiguration::SetProfileTimesteps (vector< unsigned long > const & vec) inline
Definition at line 563 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetRandomFactor()
void CConfiguration::SetRandomFactor (double d) inline
Definition at line 542 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetRandomSeed()
void CConfiguration::SetRandomSeed (int n) inline
Definition at line 209 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetRasterFiles()
void CConfiguration::SetRasterFiles (vector< string > const & vec) inline
Definition at line 227 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetRasterFormat()
void CConfiguration::SetRasterFormat (string const & str) inline
Definition at line 231 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetRunName()
void CConfiguration::SetRunName (string const & str) inline
Definition at line 181 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetRunupEquation()
void CConfiguration::SetRunupEquation (string const & str) inline
Definition at line 497 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSandErosivity()
void CConfiguration::SetSandErosivity (double d) inline
Definition at line 431 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSandMedianSize()
void CConfiguration::SetSandMedianSize (double d) inline
Definition at line 411 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSaveDigitsMode()
void CConfiguration::SetSaveDigitsMode (string const & str) inline
Definition at line 223 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSaveParallelProfiles()
void CConfiguration::SetSaveParallelProfiles (bool b) inline
Definition at line 567 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSaveProfileData()
void CConfiguration::SetSaveProfileData (bool b) inline
Definition at line 555 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSaveTimes()
void CConfiguration::SetSaveTimes (vector< string > const & vec) inline
Definition at line 205 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetScaleValues()
void CConfiguration::SetScaleValues (bool b) inline
Definition at line 239 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSeawaterDensity()
void CConfiguration::SetSeawaterDensity (double d) inline
Definition at line 341 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSedimentDensity()
void CConfiguration::SetSedimentDensity (double d) inline
Definition at line 419 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSedimentInput()
void CConfiguration::SetSedimentInput (bool b) inline
Definition at line 517 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSedimentInputDetails()
void CConfiguration::SetSedimentInputDetails (string const & str) inline
Definition at line 529 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSedimentInputLocation()
void CConfiguration::SetSedimentInputLocation (string const & str) inline
Definition at line 521 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSedimentInputType()
void CConfiguration::SetSedimentInputType (string const & str) inline
Definition at line 525 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSliceElevations()
void CConfiguration::SetSliceElevations (vector< double > const & vec) inline
Definition at line 243 of file configuration.h.
SetStartDateTime()
void CConfiguration::SetStartDateTime (string const & str) inline
Definition at line 193 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetStartDepthRatio()
void CConfiguration::SetStartDepthRatio (double d) inline
Definition at line 550 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetSuspendedSedFile()
void CConfiguration::SetSuspendedSedFile (string const & str) inline
Definition at line 320 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetTalusWidth()
void CConfiguration::SetTalusWidth (double d) inline
Definition at line 472 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetTideDataFile()
void CConfiguration::SetTideDataFile (string const & str) inline
Definition at line 377 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetTimeSeriesFiles()
void CConfiguration::SetTimeSeriesFiles (vector< string > const & vec) inline
Definition at line 255 of file configuration.h.
SetTimestep()
void CConfiguration::SetTimestep (string const & str) inline
Definition at line 201 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetTransportKLS()
void CConfiguration::SetTransportKLS (double d) inline
Definition at line 439 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetUnconsCoarseFiles()
void CConfiguration::SetUnconsCoarseFiles (vector< string > const & vec) inline
Definition at line 304 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetUnconsFineFiles()
void CConfiguration::SetUnconsFineFiles (vector< string > const & vec) inline
Definition at line 296 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetUnconsSandFiles()
void CConfiguration::SetUnconsSandFiles (vector< string > const & vec) inline
Definition at line 300 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetVectorFiles()
void CConfiguration::SetVectorFiles (vector< string > const & vec) inline
Definition at line 247 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetVectorFormat()
void CConfiguration::SetVectorFormat (string const & str) inline
Definition at line 251 of file configuration.h.
SetWaveHeightTimeSeries()
void CConfiguration::SetWaveHeightTimeSeries (string const & str) inline
Definition at line 356 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetWavePeriod()
void CConfiguration::SetWavePeriod (double d) inline
Definition at line 372 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetWavePropagationModel()
void CConfiguration::SetWavePropagationModel (int n) inline
Definition at line 337 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetWaveStationDataFile()
void CConfiguration::SetWaveStationDataFile (string const & str) inline
Definition at line 360 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
SetWorldFile()
void CConfiguration::SetWorldFile (bool b) inline
Definition at line 235 of file configuration.h.
Referenced by CSimulation::bConfigureFromYamlFile().
UseSystemTimeForRandomSeed()
bool CConfiguration::UseSystemTimeForRandomSeed () const inline
Definition at line 630 of file configuration.h.
Referenced by CSimulation::bApplyConfiguration().
UseSystemTimeForSeed()
void CConfiguration::UseSystemTimeForSeed () inline
Definition at line 214 of file configuration.h.
Field Documentation
m_bBeachSedimentTransport
bool CConfiguration::m_bBeachSedimentTransport private
Definition at line 116 of file configuration.h.
Referenced by GetBeachSedimentTransport(), InitializeDefaults(), and SetBeachSedimentTransport().
m_bCliffCollapse
bool CConfiguration::m_bCliffCollapse private
Definition at line 132 of file configuration.h.
Referenced by GetCliffCollapse(), InitializeDefaults(), and SetCliffCollapse().
m_bCoastPlatformErosion
bool CConfiguration::m_bCoastPlatformErosion private
Definition at line 114 of file configuration.h.
Referenced by GetCoastPlatformErosion(), InitializeDefaults(), and SetCoastPlatformErosion().
m_bCSVPerTimestepResults
bool CConfiguration::m_bCSVPerTimestepResults private
Definition at line 50 of file configuration.h.
Referenced by GetCSVPerTimestepResults(), InitializeDefaults(), and SetCSVPerTimestepResults().
m_bFloodInput
bool CConfiguration::m_bFloodInput private
Definition at line 142 of file configuration.h.
Referenced by GetFloodInput(), InitializeDefaults(), and SetFloodInput().
m_bHasFinalWaterLevel
bool CConfiguration::m_bHasFinalWaterLevel private
Definition at line 100 of file configuration.h.
Referenced by HasFinalWaterLevel(), InitializeDefaults(), and SetFinalWaterLevel().
m_bOutputErosionPotential
bool CConfiguration::m_bOutputErosionPotential private
Definition at line 167 of file configuration.h.
Referenced by GetOutputErosionPotential(), InitializeDefaults(), and SetOutputErosionPotential().
m_bSaveParallelProfiles
bool CConfiguration::m_bSaveParallelProfiles private
Definition at line 166 of file configuration.h.
Referenced by GetSaveParallelProfiles(), InitializeDefaults(), and SetSaveParallelProfiles().
m_bSaveProfileData
bool CConfiguration::m_bSaveProfileData private
Definition at line 163 of file configuration.h.
Referenced by GetSaveProfileData(), InitializeDefaults(), and SetSaveProfileData().
m_bScaleValues
bool CConfiguration::m_bScaleValues private
Definition at line 66 of file configuration.h.
Referenced by GetScaleValues(), InitializeDefaults(), and SetScaleValues().
m_bSedimentInput
bool CConfiguration::m_bSedimentInput private
Definition at line 150 of file configuration.h.
Referenced by GetSedimentInput(), InitializeDefaults(), and SetSedimentInput().
m_bUseSystemTimeForSeed
bool CConfiguration::m_bUseSystemTimeForSeed private
Definition at line 58 of file configuration.h.
Referenced by InitializeDefaults(), SetRandomSeed(), UseSystemTimeForRandomSeed(), and UseSystemTimeForSeed().
m_bWorldFile
bool CConfiguration::m_bWorldFile private
Definition at line 65 of file configuration.h.
Referenced by GetWorldFile(), InitializeDefaults(), and SetWorldFile().
m_dBeachSedimentPorosity
double CConfiguration::m_dBeachSedimentPorosity private
Definition at line 123 of file configuration.h.
Referenced by GetBeachSedimentPorosity(), InitializeDefaults(), and SetBeachSedimentPorosity().
m_dBermHeight
double CConfiguration::m_dBermHeight private
Definition at line 129 of file configuration.h.
Referenced by GetBermHeight(), InitializeDefaults(), and SetBermHeight().
m_dBreakingWaveRatio
double CConfiguration::m_dBreakingWaveRatio private
Definition at line 111 of file configuration.h.
Referenced by GetBreakingWaveRatio(), InitializeDefaults(), and SetBreakingWaveRatio().
m_dCliffDepositionA
double CConfiguration::m_dCliffDepositionA private
Definition at line 136 of file configuration.h.
Referenced by GetCliffDepositionA(), InitializeDefaults(), and SetCliffDepositionA().
m_dCliffErosionResistance
double CConfiguration::m_dCliffErosionResistance private
Definition at line 133 of file configuration.h.
Referenced by GetCliffErosionResistance(), InitializeDefaults(), and SetCliffErosionResistance().
m_dCliffSlopeLimit
double CConfiguration::m_dCliffSlopeLimit private
Definition at line 174 of file configuration.h.
Referenced by GetCliffSlopeLimit(), InitializeDefaults(), and SetCliffSlopeLimit().
m_dCoarseErosivity
double CConfiguration::m_dCoarseErosivity private
Definition at line 126 of file configuration.h.
Referenced by GetCoarseErosivity(), InitializeDefaults(), and SetCoarseErosivity().
m_dCoarseMedianSize
double CConfiguration::m_dCoarseMedianSize private
Definition at line 121 of file configuration.h.
Referenced by GetCoarseMedianSize(), InitializeDefaults(), and SetCoarseMedianSize().
m_dDeepWaterWaveHeight
double CConfiguration::m_dDeepWaterWaveHeight private
Definition at line 105 of file configuration.h.
Referenced by GetDeepWaterWaveHeight(), InitializeDefaults(), and SetDeepWaterWaveHeight().
m_dDeepWaterWaveOrientation
double CConfiguration::m_dDeepWaterWaveOrientation private
Definition at line 106 of file configuration.h.
Referenced by GetDeepWaterWaveOrientation(), InitializeDefaults(), and SetDeepWaterWaveOrientation().
m_dFinalWaterLevel
double CConfiguration::m_dFinalWaterLevel private
Definition at line 99 of file configuration.h.
Referenced by GetFinalWaterLevel(), and SetFinalWaterLevel().
m_dFineErosivity
double CConfiguration::m_dFineErosivity private
Definition at line 124 of file configuration.h.
Referenced by GetFineErosivity(), InitializeDefaults(), and SetFineErosivity().
m_dFineMedianSize
double CConfiguration::m_dFineMedianSize private
Definition at line 119 of file configuration.h.
Referenced by GetFineMedianSize(), InitializeDefaults(), and SetFineMedianSize().
m_dGravitationalAcceleration
double CConfiguration::m_dGravitationalAcceleration private
Definition at line 156 of file configuration.h.
Referenced by GetGravitationalAcceleration(), InitializeDefaults(), and SetGravitationalAcceleration().
m_dInitialWaterLevel
double CConfiguration::m_dInitialWaterLevel private
Definition at line 98 of file configuration.h.
Referenced by GetInitialWaterLevel(), InitializeDefaults(), and SetInitialWaterLevel().
m_dKamphuis
double CConfiguration::m_dKamphuis private
Definition at line 128 of file configuration.h.
Referenced by GetKamphuis(), InitializeDefaults(), and SetKamphuis().
m_dMaxBeachElevation
double CConfiguration::m_dMaxBeachElevation private
Definition at line 79 of file configuration.h.
Referenced by GetMaxBeachElevation(), InitializeDefaults(), and SetMaxBeachElevation().
m_dMaxLocalSlope
double CConfiguration::m_dMaxLocalSlope private
Definition at line 78 of file configuration.h.
Referenced by GetMaxLocalSlope(), InitializeDefaults(), and SetMaxLocalSlope().
m_dMinTalusHeight
double CConfiguration::m_dMinTalusHeight private
Definition at line 139 of file configuration.h.
Referenced by GetMinTalusHeight(), InitializeDefaults(), and SetMinTalusHeight().
m_dMinTalusLength
double CConfiguration::m_dMinTalusLength private
Definition at line 138 of file configuration.h.
Referenced by GetMinTalusLength(), InitializeDefaults(), and SetMinTalusLength().
m_dNormalLength
double CConfiguration::m_dNormalLength private
Definition at line 159 of file configuration.h.
Referenced by GetNormalLength(), InitializeDefaults(), and SetNormalLength().
m_dNormalSpacing
double CConfiguration::m_dNormalSpacing private
Definition at line 157 of file configuration.h.
Referenced by GetNormalSpacing(), InitializeDefaults(), and SetNormalSpacing().
m_dNotchBase
double CConfiguration::m_dNotchBase private
Definition at line 135 of file configuration.h.
Referenced by GetNotchBase(), InitializeDefaults(), and SetNotchBase().
m_dNotchOverhang
double CConfiguration::m_dNotchOverhang private
Definition at line 134 of file configuration.h.
Referenced by GetNotchOverhang(), InitializeDefaults(), and SetNotchOverhang().
m_dPlatformErosionResistance
double CConfiguration::m_dPlatformErosionResistance private
Definition at line 115 of file configuration.h.
Referenced by GetPlatformErosionResistance(), InitializeDefaults(), and SetPlatformErosionResistance().
m_dRandomFactor
double CConfiguration::m_dRandomFactor private
Definition at line 158 of file configuration.h.
Referenced by GetRandomFactor(), InitializeDefaults(), and SetRandomFactor().
m_dSandErosivity
double CConfiguration::m_dSandErosivity private
Definition at line 125 of file configuration.h.
Referenced by GetSandErosivity(), InitializeDefaults(), and SetSandErosivity().
m_dSandMedianSize
double CConfiguration::m_dSandMedianSize private
Definition at line 120 of file configuration.h.
Referenced by GetSandMedianSize(), InitializeDefaults(), and SetSandMedianSize().
m_dSeawaterDensity
double CConfiguration::m_dSeawaterDensity private
Definition at line 97 of file configuration.h.
Referenced by GetSeawaterDensity(), InitializeDefaults(), and SetSeawaterDensity().
m_dSedimentDensity
double CConfiguration::m_dSedimentDensity private
Definition at line 122 of file configuration.h.
Referenced by GetSedimentDensity(), InitializeDefaults(), and SetSedimentDensity().
m_dStartDepthRatio
double CConfiguration::m_dStartDepthRatio private
Definition at line 160 of file configuration.h.
Referenced by GetStartDepthRatio(), InitializeDefaults(), and SetStartDepthRatio().
m_dTalusWidth
double CConfiguration::m_dTalusWidth private
Definition at line 137 of file configuration.h.
Referenced by GetTalusWidth(), InitializeDefaults(), and SetTalusWidth().
m_dTransportKLS
double CConfiguration::m_dTransportKLS private
Definition at line 127 of file configuration.h.
Referenced by GetTransportKLS(), InitializeDefaults(), and SetTransportKLS().
m_dWavePeriod
double CConfiguration::m_dWavePeriod private
Definition at line 107 of file configuration.h.
Referenced by GetWavePeriod(), InitializeDefaults(), and SetWavePeriod().
m_nBeachErosionEquation
int CConfiguration::m_nBeachErosionEquation private
Definition at line 118 of file configuration.h.
Referenced by GetBeachErosionEquation(), InitializeDefaults(), and SetBeachErosionEquation().
m_nBeachTransportAtEdges
int CConfiguration::m_nBeachTransportAtEdges private
Definition at line 117 of file configuration.h.
Referenced by GetBeachTransportAtEdges(), InitializeDefaults(), and SetBeachTransportAtEdges().
m_nCliffEdgePolynomialOrder
int CConfiguration::m_nCliffEdgePolynomialOrder private
Definition at line 173 of file configuration.h.
Referenced by GetCliffEdgePolynomialOrder(), InitializeDefaults(), and SetCliffEdgePolynomialOrder().
m_nCliffEdgeSmoothing
int CConfiguration::m_nCliffEdgeSmoothing private
Definition at line 171 of file configuration.h.
Referenced by GetCliffEdgeSmoothing(), InitializeDefaults(), and SetCliffEdgeSmoothing().
m_nCliffEdgeSmoothingWindow
int CConfiguration::m_nCliffEdgeSmoothingWindow private
Definition at line 172 of file configuration.h.
Referenced by GetCliffEdgeSmoothingWindow(), InitializeDefaults(), and SetCliffEdgeSmoothingWindow().
m_nCoastlineSmoothing
int CConfiguration::m_nCoastlineSmoothing private
Definition at line 73 of file configuration.h.
Referenced by GetCoastlineSmoothing(), InitializeDefaults(), and SetCoastlineSmoothing().
m_nCoastlineSmoothingWindow
int CConfiguration::m_nCoastlineSmoothingWindow private
Definition at line 74 of file configuration.h.
Referenced by GetCoastlineSmoothingWindow(), InitializeDefaults(), and SetCoastlineSmoothingWindow().
m_nCurvatureWindow
int CConfiguration::m_nCurvatureWindow private
Definition at line 168 of file configuration.h.
Referenced by GetCurvatureWindow(), InitializeDefaults(), and SetCurvatureWindow().
m_nLogFileDetail
int CConfiguration::m_nLogFileDetail private
Definition at line 49 of file configuration.h.
Referenced by GetLogFileDetail(), InitializeDefaults(), and SetLogFileDetail().
m_nMaxSaveDigits
int CConfiguration::m_nMaxSaveDigits private
Definition at line 61 of file configuration.h.
Referenced by GetMaxSaveDigits(), InitializeDefaults(), and SetMaxSaveDigits().
m_nNumLayers
int CConfiguration::m_nNumLayers private
Definition at line 82 of file configuration.h.
Referenced by GetNumLayers(), InitializeDefaults(), and SetNumLayers().
m_nPolynomialOrder
int CConfiguration::m_nPolynomialOrder private
Definition at line 75 of file configuration.h.
Referenced by GetPolynomialOrder(), InitializeDefaults(), and SetPolynomialOrder().
m_nProfileSmoothingWindow
int CConfiguration::m_nProfileSmoothingWindow private
Definition at line 77 of file configuration.h.
Referenced by GetProfileSmoothingWindow(), InitializeDefaults(), and SetProfileSmoothingWindow().
m_nRandomSeed
int CConfiguration::m_nRandomSeed private
Definition at line 57 of file configuration.h.
Referenced by GetRandomSeed(), InitializeDefaults(), and SetRandomSeed().
m_nWavePropagationModel
int CConfiguration::m_nWavePropagationModel private
Definition at line 96 of file configuration.h.
Referenced by GetWavePropagationModel(), InitializeDefaults(), and SetWavePropagationModel().
m_strBasementDEMFile
string CConfiguration::m_strBasementDEMFile private
Definition at line 83 of file configuration.h.
Referenced by GetBasementDEMFile(), InitializeDefaults(), and SetBasementDEMFile().
m_strDuration
string CConfiguration::m_strDuration private
Definition at line 54 of file configuration.h.
Referenced by GetDuration(), InitializeDefaults(), and SetDuration().
m_strFloodCoastline
string CConfiguration::m_strFloodCoastline private
Definition at line 143 of file configuration.h.
Referenced by GetFloodCoastline(), InitializeDefaults(), and SetFloodCoastline().
m_strFloodInputLocation
string CConfiguration::m_strFloodInputLocation private
Definition at line 146 of file configuration.h.
Referenced by GetFloodInputLocation(), InitializeDefaults(), and SetFloodInputLocation().
m_strFloodLocations
string CConfiguration::m_strFloodLocations private
Definition at line 145 of file configuration.h.
Referenced by GetFloodLocations(), InitializeDefaults(), and SetFloodLocations().
m_strInterventionClassFile
string CConfiguration::m_strInterventionClassFile private
Definition at line 92 of file configuration.h.
Referenced by GetInterventionClassFile(), InitializeDefaults(), and SetInterventionClassFile().
m_strInterventionHeightFile
string CConfiguration::m_strInterventionHeightFile private
Definition at line 93 of file configuration.h.
Referenced by GetInterventionHeightFile(), InitializeDefaults(), and SetInterventionHeightFile().
m_strLandformFile
string CConfiguration::m_strLandformFile private
Definition at line 91 of file configuration.h.
Referenced by GetLandformFile(), InitializeDefaults(), and SetLandformFile().
m_strOmitGridEdges
string CConfiguration::m_strOmitGridEdges private
Definition at line 76 of file configuration.h.
Referenced by GetOmitGridEdges(), InitializeDefaults(), and SetOmitGridEdges().
m_strRasterFormat
string CConfiguration::m_strRasterFormat private
Definition at line 64 of file configuration.h.
Referenced by GetRasterFormat(), InitializeDefaults(), and SetRasterFormat().
m_strRunName
string CConfiguration::m_strRunName private
Definition at line 48 of file configuration.h.
Referenced by GetRunName(), InitializeDefaults(), and SetRunName().
m_strRunupEquation
int CConfiguration::m_strRunupEquation private
Definition at line 144 of file configuration.h.
Referenced by GetRunupEquation(), InitializeDefaults(), and SetRunupEquation().
m_strSaveDigitsMode
string CConfiguration::m_strSaveDigitsMode private
Definition at line 62 of file configuration.h.
Referenced by GetSaveDigitsMode(), InitializeDefaults(), and SetSaveDigitsMode().
m_strSedimentInputDetails
string CConfiguration::m_strSedimentInputDetails private
Definition at line 153 of file configuration.h.
Referenced by GetSedimentInputDetails(), InitializeDefaults(), and SetSedimentInputDetails().
m_strSedimentInputLocation
string CConfiguration::m_strSedimentInputLocation private
Definition at line 151 of file configuration.h.
Referenced by GetSedimentInputLocation(), InitializeDefaults(), and SetSedimentInputLocation().
m_strSedimentInputType
string CConfiguration::m_strSedimentInputType private
Definition at line 152 of file configuration.h.
Referenced by GetSedimentInputType(), InitializeDefaults(), and SetSedimentInputType().
m_strStartDateTime
string CConfiguration::m_strStartDateTime private
Definition at line 53 of file configuration.h.
Referenced by GetStartDateTime(), InitializeDefaults(), and SetStartDateTime().
m_strSuspendedSedFile
string CConfiguration::m_strSuspendedSedFile private
Definition at line 90 of file configuration.h.
Referenced by GetSuspendedSedFile(), InitializeDefaults(), and SetSuspendedSedFile().
m_strTideDataFile
string CConfiguration::m_strTideDataFile private
Definition at line 110 of file configuration.h.
Referenced by GetTideDataFile(), InitializeDefaults(), and SetTideDataFile().
m_strTimestep
string CConfiguration::m_strTimestep private
Definition at line 55 of file configuration.h.
Referenced by GetTimestep(), InitializeDefaults(), and SetTimestep().
m_strVectorFormat
string CConfiguration::m_strVectorFormat private
Definition at line 69 of file configuration.h.
Referenced by GetVectorFormat(), InitializeDefaults(), and SetVectorFormat().
m_strWaveHeightTimeSeries
string CConfiguration::m_strWaveHeightTimeSeries private
Definition at line 103 of file configuration.h.
Referenced by GetWaveHeightTimeSeries(), InitializeDefaults(), and SetWaveHeightTimeSeries().
m_strWaveStationDataFile
string CConfiguration::m_strWaveStationDataFile private
Definition at line 104 of file configuration.h.
Referenced by GetWaveStationDataFile(), InitializeDefaults(), and SetWaveStationDataFile().
m_vecConsCoarseFiles
vector<string> CConfiguration::m_vecConsCoarseFiles private
Definition at line 89 of file configuration.h.
Referenced by GetConsCoarseFiles(), InitializeDefaults(), and SetConsCoarseFiles().
m_vecConsFineFiles
vector<string> CConfiguration::m_vecConsFineFiles private
Definition at line 87 of file configuration.h.
Referenced by GetConsFineFiles(), InitializeDefaults(), and SetConsFineFiles().
m_vecConsSandFiles
vector<string> CConfiguration::m_vecConsSandFiles private
Definition at line 88 of file configuration.h.
Referenced by GetConsSandFiles(), InitializeDefaults(), and SetConsSandFiles().
m_vecFloodFiles
vector<string> CConfiguration::m_vecFloodFiles private
Definition at line 147 of file configuration.h.
Referenced by SetFloodFiles().
m_vecProfileNumbers
vector<int> CConfiguration::m_vecProfileNumbers private
Definition at line 164 of file configuration.h.
Referenced by GetProfileNumbers(), InitializeDefaults(), and SetProfileNumbers().
m_vecProfileTimesteps
vector<unsigned long> CConfiguration::m_vecProfileTimesteps private
Definition at line 165 of file configuration.h.
Referenced by GetProfileTimesteps(), InitializeDefaults(), and SetProfileTimesteps().
m_vecRasterFiles
vector<string> CConfiguration::m_vecRasterFiles private
Definition at line 63 of file configuration.h.
Referenced by GetRasterFiles(), InitializeDefaults(), and SetRasterFiles().
m_vecSaveTimes
vector<string> CConfiguration::m_vecSaveTimes private
Definition at line 56 of file configuration.h.
Referenced by GetSaveTimes(), InitializeDefaults(), and SetSaveTimes().
m_vecSliceElevations
vector<double> CConfiguration::m_vecSliceElevations private
Definition at line 67 of file configuration.h.
Referenced by GetSliceElevations(), InitializeDefaults(), and SetSliceElevations().
m_vecTimeSeriesFiles
vector<string> CConfiguration::m_vecTimeSeriesFiles private
Definition at line 70 of file configuration.h.
Referenced by InitializeDefaults(), and SetTimeSeriesFiles().
m_vecUnconsCoarseFiles
vector<string> CConfiguration::m_vecUnconsCoarseFiles private
Definition at line 86 of file configuration.h.
Referenced by GetUnconsCoarseFiles(), InitializeDefaults(), and SetUnconsCoarseFiles().
m_vecUnconsFineFiles
vector<string> CConfiguration::m_vecUnconsFineFiles private
Definition at line 84 of file configuration.h.
Referenced by GetUnconsFineFiles(), InitializeDefaults(), and SetUnconsFineFiles().
m_vecUnconsSandFiles
vector<string> CConfiguration::m_vecUnconsSandFiles private
Definition at line 85 of file configuration.h.
Referenced by GetUnconsSandFiles(), InitializeDefaults(), and SetUnconsSandFiles().
m_vecVectorFiles
vector<string> CConfiguration::m_vecVectorFiles private
Definition at line 68 of file configuration.h.
Referenced by GetFloodFiles(), GetTimeSeriesFiles(), GetVectorFiles(), InitializeDefaults(), and SetVectorFiles().
The documentation for this class was generated from the following files:
configuration.h
configuration.cpp