CoastalME (Coastal Modelling Environment): nanoflann C++ library for KD-trees
nanoflann C++ library for KD-trees
Topics
Result set classes
Load/save auxiliary functions
Metric (distance) classes
Parameter structs
Memory allocation
Auxiliary metaprogramming stuff
KD-tree classes and adaptors
Data Structures
struct nanoflann::has_resize< T, typename >
struct nanoflann::has_resize< T, decltype((void) std::declval< T >().resize(1), 0)>
struct nanoflann::has_assign< T, typename >
struct nanoflann::has_assign< T, decltype((void) std::declval< T >().assign(1, 0), 0)>
struct nanoflann::IndexDist_Sorter
struct nanoflann::ResultItem< IndexType, DistanceType >
class nanoflann::KDTreeBaseClass< Derived, Distance, DatasetAdaptor, DIM, index_t >
Functions
template<typename T>
T nanoflann::pi_const ()
template<typename Container>
std::enable_if< has_resize< Container >::value, void >::type nanoflann::resize (Container &c, const size_t nElements)
template<typename Container, typename T>
std::enable_if< has_assign< Container >::value, void >::type nanoflann::assign (Container &c, const size_t nElements, const T &value)
Detailed Description
Function Documentation
assign()
template<typename Container, typename T> std::enable_if< has_assign< Container >::value, void >::type nanoflann::assign (Container & c, const size_t nElements, const T & value) inline
Free function to assign to a container
Definition at line 144 of file nanoflann.hpp.
pi_const()
template<typename T> T nanoflann::pi_const ()
the PI constant (required to avoid MSVC missing symbols)
Definition at line 87 of file nanoflann.hpp.
Referenced by nanoflann::SO2_Adaptor< T, DataSource, T, IndexType >::accum_dist().
resize()
template<typename Container> std::enable_if< has_resize< Container >::value, void >::type nanoflann::resize (Container & c, const size_t nElements) inline
Free function to resize a resizable object
Definition at line 122 of file nanoflann.hpp.
Referenced by nanoflann::KDTreeSingleIndexAdaptor< metric_t, self_t, row_major ? MatrixType::ColsAtCompileTime :MatrixType::RowsAtCompileTime, IndexType >::computeBoundingBox(), and nanoflann::KDTreeSingleIndexDynamicAdaptor_< Distance, DatasetAdaptor, DIM, IndexType >::computeBoundingBox().