CoastalME (Coastal Modelling Environment): CGeomCoastPolygon Class Reference
CGeomCoastPolygon Class Reference
Geometry class used for coast polygon objects.
#include <coast_polygon.h>
Inherits CA2DShape.
Public Member Functions
CGeomCoastPolygon (int const, int const, int const, int const, vector< CGeom2DPoint > const *, int const, int const, CGeom2DIPoint const *, CGeom2DIPoint const *, bool const, bool const)
Constructor with 10 parameters and initialisation list.
~CGeomCoastPolygon (void) override
Destructor.
void SetDownCoastThisIter (bool const)
Set a flag to say whether sediment movement on this polygon is down-coast this iteration.
bool bDownCoastThisIter (void) const
Is sediment movement on this polygon down-coast this iteration?
bool bIsCoastEndPolygon (void) const
Is this polygon the coast-end polygon?
bool bIsCoastStartPolygon (void) const
Is this polygon the coast-start polygon?
int nGetPolygonCoastID (void) const
Get the coast ID, this is the same as the down-coast sequence of polygons.
int nGetNodeCoastPoint (void) const
Get the coast node point.
CGeom2DIPoint * pPtiGetNode (void)
Get the grid coordinates of the cell on which the node sits.
CGeom2DIPoint * pPtiGetAntiNode (void)
Get the anti-node (raster grid CRS) which is at other (seaward) end of the polygon from the node.
void SetLength (double const)
Sets the polygon's length.
double dGetLength (void) const
Gets the polygon's length.
void SetNumCellsInPolygon (int const)
Set the number of cells in the polygon.
int nGetUpCoastProfile (void) const
Return the number of the up-coast profile.
int nGetDownCoastProfile (void) const
Return the number of the down-coast profile.
CGeom2DPoint * pPtGetBoundaryPoint (int const)
Get the coordinates (external CRS) of a specified point on the polygon's boundary.
int nGetBoundarySize (void) const
Get the number of points in the polygon's boundary.
int nGetNumPointsUsedUpCoastProfile (void) const
Return the number of points in the up-coast profile.
int nGetNumPointsUsedDownCoastProfile (void) const
Return the number of points in the down-coast profile.
void SetSeawaterVolume (const double)
Set the volume of seawater in the coast polygon.
double dGetSeawaterVolume (void) const
Get the volume of seawater in the coast polygon.
void AddPotentialErosion (double const)
Adds in potential beach erosion of unconsolidated sediment (all size classes) on this polygon (m_dPotentialBeachErosionAllUncons is <= 0)
double dGetPotentialErosion (void) const
Returns this timestep's total change in depth of unconsolidated sediment (all size classes) due to beach erosion on this polygon (m_dPotentialBeachErosionAllUncons <= 0)
void SetBeachErosionUnconsFine (double const)
Sets a value (must be < 0) for this timestep's erosion of fine unconsolidated sediment (beach redistribution only) on this polygon.
double dGetBeachErosionUnconsFine (void) const
Returns this timestep's erosion (a value < 0) of fine unconsolidated sediment (beach redistribution only) on this polygon.
void SetBeachErosionUnconsSand (double const)
Sets a value (must be < 0) for this timestep's erosion of sand-sized unconsolidated sediment (beach redistribution only) on this polygon. This includes sand sediment eroded during Dean profile deposition of sand sediment.
double dGetBeachErosionUnconsSand (void) const
Returns this timestep's erosion (a value < 0) of sand-sized unconsolidated sediment (beach redistribution only) on this polygon. This includes sand sediment eroded during Dean profile deposition of sand sediment.
void SetBeachErosionUnconsCoarse (double const)
Sets a value (must be < 0) for this timestep's erosion of coarse unconsolidated sediment (beach redistribution only) on this polygon. This includes coarse sediment eroded during Dean profile deposition of coarse sediment.
double dGetBeachErosionUnconsCoarse (void) const
Returns this timestep's erosion (a value < 0) of coarse unconsolidated sediment (beach redistribution only) on this polygon. This includes coarse sediment eroded during Dean profile deposition of coarse sediment.
double dGeBeachErosionAllUncons (void) const
Returns this timestep's total (all size classes) beach erosion of unconsolidated sediment on this polygon, as a -ve depth in m.
void SetBeachDepositionUnconsSand (double const)
Sets the depth of sand-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
double dGetBeachDepositionUnconsSand (void) const
Returns the depth of sand-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
void SetBeachDepositionUnconsCoarse (double const)
Sets the depth of coarse-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
double dGetBeachDepositionUnconsCoarse (void) const
Returns the depth of coarse-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
double dGetSuspensionUnconsFine (void) const
Returns this timestep's to-suspension movement of fine unconsolidated sediment on this polygon, as a +ve depth in m.
void SetZeroToDoDepositionUnconsSand (void)
Re-initialises this timestep's still-to-do deposition of unconsolidated sand sediment (from beach redistribution only) on this polygon.
void AddToDoBeachDepositionUnconsSand (double const)
Adds a depth (in m) of sand-sized unconsolidated sediment to this timestep's still-to-do deposition of unconsolidated sand sediment (from beach redistribution only) on this polygon.
double dGetToDoBeachDepositionUnconsSand (void) const
Returns this timestep's still-to-do deposition of sand-sized unconsolidated sediment (from beach redistribution only) on this polygon, as a +ve depth in m.
void SetZeroToDoDepositionUnconsCoarse (void)
Re-initialises this timestep's still-to-do deposition of unconsolidated coarse sediment (from beach redistribution only) on this polygon.
void AddToDoBeachDepositionUnconsCoarse (double const)
Adds a depth (in m) of coarse unconsolidated sediment to this timestep's still-to-do deposition of unconsolidated coarse sediment (from beach redistribution only) on this polygon.
double dGetToDoBeachDepositionUnconsCoarse (void) const
Returns this timestep's still-to-do deposition of coarse unconsolidated sediment (from beach redistribution only) on this polygon, as a +ve depth in m.
double dGetBeachDepositionAndSuspensionAllUncons (void) const
Returns this timestep's total (all size classes) deposition and to-suspension movement of unconsolidated sediment (from beach redistribution only) on this polygon, as a +ve depth in m.
void AddBeachSandErodedDeanProfile (double const)
Adds a depth (in m) of sand sediment eroded during beach Dean profile deposition.
double dGetBeachSandErodedDeanProfile (void) const
Returns the depth (in m) of sand sediment eroded during beach Dean profile deposition.
void AddBeachCoarseErodedDeanProfile (double const)
Adds a depth (in m) of coarse sediment eroded during beach Dean profile deposition.
double dGetBeachCoarseErodedDeanProfile (void) const
Returns the depth (in m) of coarse sediment eroded during beach Dean profile deposition.
void SetUpCoastAdjacentPolygons (vector< int > const *)
Sets all up-coast adjacent polygons.
int nGetUpCoastAdjacentPolygon (int const) const
Gets a single up-coast adjacent polygon.
int nGetNumUpCoastAdjacentPolygons (void) const
Gets all up-coast adjacent polygons.
void SetDownCoastAdjacentPolygons (vector< int > const *)
Sets all down-coast adjacent polygons.
int nGetDownCoastAdjacentPolygon (int const) const
Gets a single down-coast adjacent polygon.
int nGetNumDownCoastAdjacentPolygons (void) const
Gets all down-coast adjacent polygons.
void SetUpCoastAdjacentPolygonBoundaryShares (vector< double > const *)
Sets the boundary shares for all up-coast adjacent polygons.
double dGetUpCoastAdjacentPolygonBoundaryShare (int const) const
Gets the boundary shares for all up-coast adjacent polygons.
void SetDownCoastAdjacentPolygonBoundaryShares (vector< double > const *)
Sets the boundary shares for all down-coast adjacent polygons.
double dGetDownCoastAdjacentPolygonBoundaryShare (int const) const
Gets the boundary shares for all down-coast adjacent polygons.
bool bDownCoastIsAlreadyPresent (int const)
Searches the list of down-coast adjacent polygons for a given polygon number.
bool bUpCoastIsAlreadyPresent (int const)
Searches the list of up-coast adjacent polygons for a given polygon number.
void SetAvgUnconsD50 (double const)
Set the average d50 for unconsolidated sediment on this polygon.
double dGetAvgUnconsD50 (void) const
Get the average d50 for unconsolidated sediment on this polygon.
void Display (void) override
Instantiates the pure virtual function in the abstract parent class, so that CGeomCoastPolygon is not an abstract class.
void AddCircularity (int const)
Add a circularity to this polygon.
vector< int > const * VnGetCircularities (void) const
Get all circularities for this polygon.
void AddCliffCollapseErosionFine (double const)
Add to the this-iteration total of unconsolidated fine sediment eroded from cliff collapse on this polygon.
double dGetCliffCollapseErosionFine (void) const
Get the this-iteration total of unconsolidated fine sediment eroded from cliff collapse on this polygon.
void AddCliffCollapseErosionSand (double const)
Add to the this-iteration total of unconsolidated sand sediment from cliff collapse on this polygon, note that this does not include sand sediment eroded during Dean profile deposition of talus.
double dGetCliffCollapseErosionSand (void) const
Get the this-iteration total of unconsolidated sand sediment from cliff collapse on this polygon, note that this does not include sand sediment eroded during Dean profile deposition of talus.
void AddCliffCollapseErosionCoarse (double const)
Add to the this-iteration total of unconsolidated coarse sediment from cliff collapse on this polygon, note that this does not include coarse sediment eroded during Dean profile deposition of talus.
double dGetCliffCollapseErosionCoarse (void) const
Get the this-iteration total of unconsolidated coarse sediment from cliff collapse on this polygon, note that this does not include coarse sediment eroded during Dean profile deposition of talus.
void AddCliffCollapseToSuspensionFine (double const)
Add to the this-iteration total of unconsolidated fine sediment from cliff collapse which goes to suspension on this polygon.
double dGetCliffCollapseToSuspensionFine (void) const
Get the this-iteration total of unconsolidated fine sediment from cliff collapse which goes to suspension on this polygon.
void AddCliffCollapseUnconsSandDeposition (double const)
Add to the this-iteration total of unconsolidated sand sediment deposited from cliff collapse on this polygon.
double dGetCliffCollapseUnconsSandDeposition (void) const
Get the this-iteration total of unconsolidated sand sediment deposited from cliff collapse on this polygon.
void AddCliffCollapseUnconsCoarseDeposition (double const)
Add to the this-iteration total of unconsolidated coarse sediment deposited from cliff collapse on this polygon.
double dGetCliffCollapseUnconsCoarseDeposition (void) const
Get the this-iteration total of unconsolidated coarse sediment deposited from cliff collapse on this polygon.
void AddCliffCollapseFineErodedDeanProfile (double const)
double dGetCliffCollapseFineErodedDeanProfile (void) const
void AddCliffCollapseSandErodedDeanProfile (double const)
Add to the this-iteration total of unconsolidated sand sediment eroded during deposition of cliff collapse talus as a Dean profile.
double dGetCliffCollapseSandErodedDeanProfile (void) const
Get the this-iteration total of unconsolidated sand sediment eroded during deposition of cliff collapse talus as a Dean profile.
void AddCliffCollapseCoarseErodedDeanProfile (double const)
Add to the this-iteration total of unconsolidated coarse sediment eroded during deposition of cliff collapse talus as a Dean profile.
double dGetCliffCollapseCoarseErodedDeanProfile (void) const
Get the this-iteration total of unconsolidated coarse sediment eroded during deposition of cliff collapse talus as a Dean profile.
void AddPlatformErosionUnconsSand (double const)
Add to the this-iteration total of unconsolidated sand sediment derived from shore platform erosion on this polygon.
double dGetPlatformErosionUnconsSand (void) const
Get the this-iteration total of unconsolidated sand sediment derived from shore platform erosion on this polygon.
void AddPlatformErosionUnconsCoarse (double const)
Add to the this-iteration total of unconsolidated coarse sediment derived from shore platform erosion on this polygon.
double dGetPlatformErosionUnconsCoarse (void) const
Get the this-iteration total of unconsolidated coarse sediment derived from shore platform erosion on this polygon.
void SetPreExistingUnconsFine (double const)
Set the value of pre-existing unconsolidated fine sediment stored on this polygon.
double dGetPreExistingUnconsFine (void) const
Get the value of pre-existing unconsolidated fine sediment stored on this polygon.
void SetPreExistingUnconsSand (double const)
Set the value of pre-existing unconsolidated sand sediment stored on this polygon.
double dGetPreExistingUnconsSand (void) const
Get the value of pre-existing unconsolidated sand sediment stored on this polygon.
void SetPreExistingUnconsCoarse (double const)
Set the value of pre-existing unconsolidated coarse sediment stored on this polygon.
double dGetPreExistingUnconsCoarse (void) const
Get the value of pre-existing unconsolidated coarse sediment stored on this polygon.
void SetPreExistingConsFine (double const)
Set the value of pre-existing consolidated fine sediment stored on this polygon.
double dGetPreExistingConsFine (void) const
Get the value of pre-existing consolidated fine sediment stored on this polygon.
void SetPreExistingConsSand (double const)
Set the value of pre-existing consolidated sand sediment stored on this polygon.
double dGetPreExistingConsSand (void) const
Get the value of pre-existing consolidated sand sediment stored on this polygon.
void SetPreExistingConsCoarse (double const)
Set the value of pre-existing consolidated coarse sediment stored on this polygon.
double dGetPreExistingConsCoarse (void) const
Get the value of pre-existing consolidated coarse sediment stored on this polygon.
void SetSedimentInputUnconsFine (double const)
Set the value of fine sediment on the polygon derived from sediment input events(s)
double dGetSedimentInputUnconsFine (void) const
Get the value of fine sediment on the polygon derived from sediment input events(s)
void SetSedimentInputUnconsSand (double const)
Set the value of sand sediment on the polygon derived from sediment input events(s)
double dGetSedimentInputUnconsSand (void) const
Get the value of sand sediment on the polygon derived from sediment input events(s)
void SetSedimentInputUnconsCoarse (double const)
Set the value of coarse sediment on the polygon derived from sediment input events(s)
double dGetSedimentInputUnconsCoarse (void) const
Get the value of coarse sediment on the polygon derived from sediment input events(s)
void AppendVertex (CGeom2DIPoint const *)
Appends the point cordinates (grid CRS) for a polygon vertex.
CGeom2DIPoint PtiGetFillStartPoint (void)
Public Member Functions inherited from CA2DShape
void Reverse (void)
Reverses the sequence of points in the vector which represents this 2D polygon.
int nGetSize (void) const
void Resize (int const)
Resizes the vector which represents this 2D shape.
void Append (CGeom2DPoint const *)
Appends a point to this 2D shape.
void Append (double const, double const)
Appends a point to this 2D shape.
void AppendIfNotPrevious (double const, double const)
Appends a point to this 2D shape only if the point is not the same as the previous point in the vector.
CGeom2DPoint * pPtBack (void)
Returns the last element of this 2D shape.
CGeom2DPoint & operator[] (int const)
Operator to return one point of this 2D shape.
vector< CGeom2DPoint > * pPtVGetPoints (void)
Returns the address of the vector which represents this 2D shape.
Private Attributes
bool m_bUnconsSedimentMovementDownCoastThisIter
Is the movement of unconsolidated sediment on this polygon down-coast (i.e. along the coast in the direction of increasing coastline point numbers) during this iteration?
bool m_bCoastEndPolygon
Is this polygon at the end of the coastline?
bool m_bCoastStartPolygon
Is this polygon at the start of the coastline?
int m_nCoastID
This-coast-only number of this polygon.
int m_nCoastNode
The point on this polygon's coastline segment with maximum concave curvature, roughly at the middle of the coastline segment.
int m_nProfileUpCoast
The normal profile which bounds the polygon in the up-coast direction.
int m_nProfileDownCoast
The normal profile which bounds the polygon in the down-coast direction.
int m_nProfileUpCoastNumPointsUsed
The number of points from the up-coast normal which are part of this polygon (less than the normal's full length if the polygon is triangular)
int m_nProfileDownCoastNumPointsUsed
The number of points from the down-coast normal which are part of this polygon (less than the normal's full length if the polygon is triangular)
int m_nNumCells
The number of cells in the polygon.
double m_dAvgUnconsD50
The average d50 of unconsolidated sediment on this polygon.
double m_dSeawaterVolume
The volume (m3) of sea water within the polygon.
double m_dPotentialBeachErosionAllUncons
Potential (ignoring supply-limitation) erosion of unconsolidated sediment (all size classes) as a depth during this timestep (-ve), beach redistribution only.
double m_dBeachErosionUnconsFine
Erosion (considering supply-limitation) of fine-sized unconsolidated sediment as a depth this timestep (-ve), beach redistribution only.
double m_dBeachErosionUnconsSand
Erosion (considering supply-limitation) of sand-sized unconsolidated sediment as a depth this timestep (-ve), beach redistribution only. This includes sand sediment eroded during Dean profile deposition of sand sediment.
double m_dBeachErosionUnconsCoarse
Erosion (considering supply-limitation) of coarse-sized unconsolidated sediment as a depth this timestep (-ve), beach redistribution only. This includes coarse sediment eroded during Dean profile deposition of coarse sediment.
double m_dBeachDepositionUnconsSand
Depth of sand-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
double m_dBeachDepositionUnconsCoarse
Depth of coarse-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
double m_dSuspensionUnconsFine
To-suspension movement of fine-sized sediment as a depth this timestep (+ve) ALL PROCESSES TODO *** CHECK *** REPLACE, INSTEAD USE TOTALS FROM TO-SUSPENSION FINE FROM (a) PLATFORM EROSION (b) CLIFF COLLAPSE (c) BEACH EROSION.
double m_dToDoBeachDepositionUnconsSand
Still-to-do depth (m) of sand-sized unconsolidated sediment to be deposited this timestep (+ve), beach redistribution only.
double m_dToDoBeachDepositionUnconsCoarse
Still-to-do depth (m) of coarse-sized unconsolidated sediment to be deposited this timestep (+ve), beach redistribution only.
double m_dBeachSandErodedDeanProfile
Depth of sand unconsolidated sediment eroded during beach deposition as a Dean profile.
double m_dBeachCoarseErodedDeanProfile
Depth of coarse unconsolidated sediment eroded during beach deposition as a Dean profile.
double m_dCliffCollapseErosionFine
Depth of eroded fine sediment from cliff collapse (is always equal to m_dCliffCollapseToSuspensionFine)
double m_dCliffCollapseErosionSand
Depth of eroded sand sediment from cliff collapse, note that this does not include sand sediment eroded during Dean profile deposition of talus.
double m_dCliffCollapseErosionCoarse
Depth of eroded coarse sediment from cliff collapse, note that this does not include coarse sediment eroded during Dean profile deposition of talus.
double m_dCliffCollapseTalusFineToSuspension
Depth of unconsolidated fine sediment which goes to suspension from cliff collapse.
double m_dCliffCollapseTalusSand
Depth of unconsolidated sand talus from cliff collapse.
double m_dCliffCollapseTalusCoarse
Depth of unconsolidated coarse talus from cliff collapse.
double m_dCliffCollapseSandErodedDeanProfile
Depth of sand unconsolidated sediment eroded during deposition of cliff collapse talus as a Dean profile.
double m_dCliffCollapseCoarseErodedDeanProfile
Depth of coarse unconsolidated sediment eroded during deposition of cliff collapse talus as a Dean profile.
double m_dPlatformErosionToSuspensionFine
Depth of fine sediment moved to suspension from shore platform erosion.
double m_dPlatformErosionUnconsSand
Depth of unconsolidated sand sediment from shore platform erosion.
double m_dPlatformErosionUnconsCoarse
Depth of unconsolidated coarse sediment from shore platform erosion.
double m_dPreExistingUnconsFine
Depth of pre-existing unconsolidated fine sediment.
double m_dPreExistingUnconsSand
Depth of pre-existing unconsolidated sand sediment.
double m_dPreExistingUnconsCoarse
Depth of pre-existing unconsolidated coarse sedimet.
double m_dPreExistingConsFine
Depth of pre-existing consolidated fine sediment.
double m_dPreExistingConsSand
Depth of pre-existing consolidated sand sediment.
double m_dPreExistingConsCoarse
Depth of pre-existing consolidated coarse sediment.
double m_dSedimentInputFine
Depth of fine sediment added from this-iteration sediment input event(s)
double m_dSedimentInputSand
Depth of sand sediment added from this-iteration sediment input event(s)
double m_dSedimentInputCoarse
Depth of coarse sediment added from this-iteration sediment input event(s)
double m_dLength
Coast polygon length.
CGeom2DIPoint m_PtiNode
Coordinates of the coast node cell (raster grid CRS)
CGeom2DIPoint m_PtiAntinode
Coordinates of the cell (raster grid CRS) which is at other (seaward) end of the polygon.
vector< int > m_VnUpCoastAdjacentPolygon
The ID(s) of the up-coast adjacent polygon(s)
vector< int > m_VnDownCoastAdjacentPolygon
The ID(s) of the down-coast adjacent polygon(s)
vector< int > m_VnCircularityWith
If this polygon has a circular unconsolidated-sediment-movement relationship with one or more other polygons, the coast-only numbers of these polygons.
vector< double > m_VdUpCoastAdjacentPolygonBoundaryShare
The boundary share(s) (0 to 1) with adjacent up-coast polygon(s)
vector< double > m_VdDownCoastAdjacentPolygonBoundaryShare
The boundary share(s) (0 to 1) with adjacent up-coast polygon(s)
vector< CGeom2DIPoint > m_VPtiVertices
The polygon's vertices (not all of them, just the ends of the profile sides), used to calculate the polygon's centroid for filling it.
Additional Inherited Members
Protected Member Functions inherited from CA2DShape
CA2DShape (void)
Constructor.
virtual ~CA2DShape (void)
Destructor.
Protected Attributes inherited from CA2DShape
vector< CGeom2DPoint > m_VPoints
The points which comprise the float-coordinate 2D shape.
Detailed Description
Geometry class used for coast polygon objects.
TODO 001 This is a more detailed description of the CRWCoast class.
Author
David Favis-Mortlock
Andres Payo
Date
2025
Copyright
GNU General Public License
Definition at line 29 of file coast_polygon.h.
Constructor & Destructor Documentation
CGeomCoastPolygon()
CGeomCoastPolygon::CGeomCoastPolygon (int const nCoastID, int const nNode, int const nProfileUpCoast, int const nProfileDownCoast, vector< CGeom2DPoint > const * pVIn, int const nLastPointUpCoast, int const nLastPointDownCoast, CGeom2DIPoint const * PtiNode, CGeom2DIPoint const * PtiAntinode, bool const bStartCoast, bool const bEndCoast)
Constructor with 10 parameters and initialisation list.
Definition at line 34 of file coast_polygon.cpp.
~CGeomCoastPolygon()
CGeomCoastPolygon::~CGeomCoastPolygon (void) override
Destructor.
Definition at line 87 of file coast_polygon.cpp.
Member Function Documentation
AddBeachCoarseErodedDeanProfile()
void CGeomCoastPolygon::AddBeachCoarseErodedDeanProfile (double const dDepth)
Adds a depth (in m) of coarse sediment eroded during beach Dean profile deposition.
Definition at line 394 of file coast_polygon.cpp.
Referenced by CSimulation::nDoParallelProfileUnconsErosion(), and CSimulation::nDoUnconsDepositionOnPolygon().
AddBeachSandErodedDeanProfile()
void CGeomCoastPolygon::AddBeachSandErodedDeanProfile (double const dDepth)
Adds a depth (in m) of sand sediment eroded during beach Dean profile deposition.
Definition at line 382 of file coast_polygon.cpp.
Referenced by CSimulation::nDoParallelProfileUnconsErosion(), and CSimulation::nDoUnconsDepositionOnPolygon().
AddCircularity()
void CGeomCoastPolygon::AddCircularity (int const nPoly)
Add a circularity to this polygon.
Definition at line 521 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
AddCliffCollapseCoarseErodedDeanProfile()
void CGeomCoastPolygon::AddCliffCollapseCoarseErodedDeanProfile (double const dDepth)
Add to the this-iteration total of unconsolidated coarse sediment eroded during deposition of cliff collapse talus as a Dean profile.
Definition at line 617 of file coast_polygon.cpp.
AddCliffCollapseErosionCoarse()
void CGeomCoastPolygon::AddCliffCollapseErosionCoarse (double const dDepth)
Add to the this-iteration total of unconsolidated coarse sediment from cliff collapse on this polygon, note that this does not include coarse sediment eroded during Dean profile deposition of talus.
Definition at line 569 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapse().
AddCliffCollapseErosionFine()
void CGeomCoastPolygon::AddCliffCollapseErosionFine (double const dDepth)
Add to the this-iteration total of unconsolidated fine sediment eroded from cliff collapse on this polygon.
Definition at line 545 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapse().
AddCliffCollapseErosionSand()
void CGeomCoastPolygon::AddCliffCollapseErosionSand (double const dDepth)
Add to the this-iteration total of unconsolidated sand sediment from cliff collapse on this polygon, note that this does not include sand sediment eroded during Dean profile deposition of talus.
Definition at line 557 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapse().
AddCliffCollapseFineErodedDeanProfile()
void CGeomCoastPolygon::AddCliffCollapseFineErodedDeanProfile (double const)
AddCliffCollapseSandErodedDeanProfile()
void CGeomCoastPolygon::AddCliffCollapseSandErodedDeanProfile (double const dDepth)
Add to the this-iteration total of unconsolidated sand sediment eroded during deposition of cliff collapse talus as a Dean profile.
Definition at line 605 of file coast_polygon.cpp.
AddCliffCollapseToSuspensionFine()
void CGeomCoastPolygon::AddCliffCollapseToSuspensionFine (double const dDepth)
Add to the this-iteration total of unconsolidated fine sediment from cliff collapse which goes to suspension on this polygon.
Definition at line 533 of file coast_polygon.cpp.
Referenced by CSimulation::nDoCliffCollapse().
AddCliffCollapseUnconsCoarseDeposition()
void CGeomCoastPolygon::AddCliffCollapseUnconsCoarseDeposition (double const dDepth)
Add to the this-iteration total of unconsolidated coarse sediment deposited from cliff collapse on this polygon.
Definition at line 593 of file coast_polygon.cpp.
AddCliffCollapseUnconsSandDeposition()
void CGeomCoastPolygon::AddCliffCollapseUnconsSandDeposition (double const dDepth)
Add to the this-iteration total of unconsolidated sand sediment deposited from cliff collapse on this polygon.
Definition at line 581 of file coast_polygon.cpp.
AddPlatformErosionUnconsCoarse()
void CGeomCoastPolygon::AddPlatformErosionUnconsCoarse (double const dDepth)
Add to the this-iteration total of unconsolidated coarse sediment derived from shore platform erosion on this polygon.
Definition at line 653 of file coast_polygon.cpp.
AddPlatformErosionUnconsSand()
void CGeomCoastPolygon::AddPlatformErosionUnconsSand (double const dDepth)
Add to the this-iteration total of unconsolidated sand sediment derived from shore platform erosion on this polygon.
Definition at line 641 of file coast_polygon.cpp.
AddPotentialErosion()
void CGeomCoastPolygon::AddPotentialErosion (double const dDepth)
Adds in potential beach erosion of unconsolidated sediment (all size classes) on this polygon (m_dPotentialBeachErosionAllUncons is <= 0)
Definition at line 250 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion().
AddToDoBeachDepositionUnconsCoarse()
void CGeomCoastPolygon::AddToDoBeachDepositionUnconsCoarse (double const dDepth)
Adds a depth (in m) of coarse unconsolidated sediment to this timestep's still-to-do deposition of unconsolidated coarse sediment (from beach redistribution only) on this polygon.
Definition at line 370 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
AddToDoBeachDepositionUnconsSand()
void CGeomCoastPolygon::AddToDoBeachDepositionUnconsSand (double const dDepth)
Adds a depth (in m) of sand-sized unconsolidated sediment to this timestep's still-to-do deposition of unconsolidated sand sediment (from beach redistribution only) on this polygon.
Definition at line 352 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
AppendVertex()
void CGeomCoastPolygon::AppendVertex (CGeom2DIPoint const * pPti)
Appends the point cordinates (grid CRS) for a polygon vertex.
Definition at line 773 of file coast_polygon.cpp.
Referenced by CSimulation::nCreateAllPolygons().
bDownCoastIsAlreadyPresent()
bool CGeomCoastPolygon::bDownCoastIsAlreadyPresent (int const nPoly)
Searches the list of down-coast adjacent polygons for a given polygon number.
Definition at line 450 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
bDownCoastThisIter()
bool CGeomCoastPolygon::bDownCoastThisIter (void) const
Is sediment movement on this polygon down-coast this iteration?
Definition at line 108 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
bIsCoastEndPolygon()
bool CGeomCoastPolygon::bIsCoastEndPolygon (void) const
Is this polygon the coast-end polygon?
Definition at line 120 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition(), and CSimulation::nDoPolygonSharedBoundaries().
bIsCoastStartPolygon()
bool CGeomCoastPolygon::bIsCoastStartPolygon (void) const
Is this polygon the coast-start polygon?
Definition at line 132 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition(), and CSimulation::nDoPolygonSharedBoundaries().
bUpCoastIsAlreadyPresent()
bool CGeomCoastPolygon::bUpCoastIsAlreadyPresent (int const nPoly)
Searches the list of up-coast adjacent polygons for a given polygon number.
Definition at line 464 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
dGeBeachErosionAllUncons()
double CGeomCoastPolygon::dGeBeachErosionAllUncons (void) const
Returns this timestep's total (all size classes) beach erosion of unconsolidated sediment on this polygon, as a -ve depth in m.
Definition at line 298 of file coast_polygon.cpp.
dGetAvgUnconsD50()
double CGeomCoastPolygon::dGetAvgUnconsD50 (void) const
Get the average d50 for unconsolidated sediment on this polygon.
Definition at line 510 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion(), and CSimulation::WritePolygonInfoTable().
dGetBeachCoarseErodedDeanProfile()
double CGeomCoastPolygon::dGetBeachCoarseErodedDeanProfile (void) const
Returns the depth (in m) of coarse sediment eroded during beach Dean profile deposition.
Definition at line 400 of file coast_polygon.cpp.
dGetBeachDepositionAndSuspensionAllUncons()
double CGeomCoastPolygon::dGetBeachDepositionAndSuspensionAllUncons (void) const
Returns this timestep's total (all size classes) deposition and to-suspension movement of unconsolidated sediment (from beach redistribution only) on this polygon, as a +ve depth in m.
Definition at line 406 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetBeachDepositionUnconsCoarse()
double CGeomCoastPolygon::dGetBeachDepositionUnconsCoarse (void) const
Returns the depth of coarse-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
Definition at line 340 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetBeachDepositionUnconsSand()
double CGeomCoastPolygon::dGetBeachDepositionUnconsSand (void) const
Returns the depth of sand-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
Definition at line 328 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetBeachErosionUnconsCoarse()
double CGeomCoastPolygon::dGetBeachErosionUnconsCoarse (void) const
Returns this timestep's erosion (a value < 0) of coarse unconsolidated sediment (beach redistribution only) on this polygon. This includes coarse sediment eroded during Dean profile deposition of coarse sediment.
Definition at line 292 of file coast_polygon.cpp.
dGetBeachErosionUnconsFine()
double CGeomCoastPolygon::dGetBeachErosionUnconsFine (void) const
Returns this timestep's erosion (a value < 0) of fine unconsolidated sediment (beach redistribution only) on this polygon.
Definition at line 268 of file coast_polygon.cpp.
dGetBeachErosionUnconsSand()
double CGeomCoastPolygon::dGetBeachErosionUnconsSand (void) const
Returns this timestep's erosion (a value < 0) of sand-sized unconsolidated sediment (beach redistribution only) on this polygon. This includes sand sediment eroded during Dean profile deposition of sand sediment.
Definition at line 280 of file coast_polygon.cpp.
dGetBeachSandErodedDeanProfile()
double CGeomCoastPolygon::dGetBeachSandErodedDeanProfile (void) const
Returns the depth (in m) of sand sediment eroded during beach Dean profile deposition.
Definition at line 388 of file coast_polygon.cpp.
dGetCliffCollapseCoarseErodedDeanProfile()
double CGeomCoastPolygon::dGetCliffCollapseCoarseErodedDeanProfile (void) const
Get the this-iteration total of unconsolidated coarse sediment eroded during deposition of cliff collapse talus as a Dean profile.
Definition at line 623 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonCliffCollapseErosion().
dGetCliffCollapseErosionCoarse()
double CGeomCoastPolygon::dGetCliffCollapseErosionCoarse (void) const
Get the this-iteration total of unconsolidated coarse sediment from cliff collapse on this polygon, note that this does not include coarse sediment eroded during Dean profile deposition of talus.
Definition at line 575 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonCliffCollapseErosion().
dGetCliffCollapseErosionFine()
double CGeomCoastPolygon::dGetCliffCollapseErosionFine (void) const
Get the this-iteration total of unconsolidated fine sediment eroded from cliff collapse on this polygon.
Definition at line 551 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonCliffCollapseErosion().
dGetCliffCollapseErosionSand()
double CGeomCoastPolygon::dGetCliffCollapseErosionSand (void) const
Get the this-iteration total of unconsolidated sand sediment from cliff collapse on this polygon, note that this does not include sand sediment eroded during Dean profile deposition of talus.
Definition at line 563 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonCliffCollapseErosion().
dGetCliffCollapseFineErodedDeanProfile()
double CGeomCoastPolygon::dGetCliffCollapseFineErodedDeanProfile (void) const
dGetCliffCollapseSandErodedDeanProfile()
double CGeomCoastPolygon::dGetCliffCollapseSandErodedDeanProfile (void) const
Get the this-iteration total of unconsolidated sand sediment eroded during deposition of cliff collapse talus as a Dean profile.
Definition at line 611 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonCliffCollapseErosion().
dGetCliffCollapseToSuspensionFine()
double CGeomCoastPolygon::dGetCliffCollapseToSuspensionFine (void) const
Get the this-iteration total of unconsolidated fine sediment from cliff collapse which goes to suspension on this polygon.
Definition at line 539 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonCliffCollapseErosion().
dGetCliffCollapseUnconsCoarseDeposition()
double CGeomCoastPolygon::dGetCliffCollapseUnconsCoarseDeposition (void) const
Get the this-iteration total of unconsolidated coarse sediment deposited from cliff collapse on this polygon.
Definition at line 599 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::WritePolygonCliffCollapseErosion().
dGetCliffCollapseUnconsSandDeposition()
double CGeomCoastPolygon::dGetCliffCollapseUnconsSandDeposition (void) const
Get the this-iteration total of unconsolidated sand sediment deposited from cliff collapse on this polygon.
Definition at line 587 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::WritePolygonCliffCollapseErosion().
dGetDownCoastAdjacentPolygonBoundaryShare()
double CGeomCoastPolygon::dGetDownCoastAdjacentPolygonBoundaryShare (int const nIndex) const
Gets the boundary shares for all down-coast adjacent polygons.
Definition at line 497 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
dGetLength()
double CGeomCoastPolygon::dGetLength (void) const
Gets the polygon's length.
Definition at line 173 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion().
dGetPlatformErosionUnconsCoarse()
double CGeomCoastPolygon::dGetPlatformErosionUnconsCoarse (void) const
Get the this-iteration total of unconsolidated coarse sediment derived from shore platform erosion on this polygon.
Definition at line 659 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::WritePolygonShorePlatformErosion().
dGetPlatformErosionUnconsSand()
double CGeomCoastPolygon::dGetPlatformErosionUnconsSand (void) const
Get the this-iteration total of unconsolidated sand sediment derived from shore platform erosion on this polygon.
Definition at line 647 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::WritePolygonShorePlatformErosion().
dGetPotentialErosion()
double CGeomCoastPolygon::dGetPotentialErosion (void) const
Returns this timestep's total change in depth of unconsolidated sediment (all size classes) due to beach erosion on this polygon (m_dPotentialBeachErosionAllUncons <= 0)
Definition at line 256 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition(), and CSimulation::WritePolygonPotentialErosion().
dGetPreExistingConsCoarse()
double CGeomCoastPolygon::dGetPreExistingConsCoarse (void) const
Get the value of pre-existing consolidated coarse sediment stored on this polygon.
Definition at line 731 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonPreExistingSedimentTable().
dGetPreExistingConsFine()
double CGeomCoastPolygon::dGetPreExistingConsFine (void) const
Get the value of pre-existing consolidated fine sediment stored on this polygon.
Definition at line 707 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonPreExistingSedimentTable().
dGetPreExistingConsSand()
double CGeomCoastPolygon::dGetPreExistingConsSand (void) const
Get the value of pre-existing consolidated sand sediment stored on this polygon.
Definition at line 719 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonPreExistingSedimentTable().
dGetPreExistingUnconsCoarse()
double CGeomCoastPolygon::dGetPreExistingUnconsCoarse (void) const
Get the value of pre-existing unconsolidated coarse sediment stored on this polygon.
Definition at line 695 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), CSimulation::nDoAllActualBeachErosionAndDeposition(), CSimulation::WritePolygonPreExistingSedimentTable(), and CSimulation::WritePolygonSedimentBeforeMovement().
dGetPreExistingUnconsFine()
double CGeomCoastPolygon::dGetPreExistingUnconsFine (void) const
Get the value of pre-existing unconsolidated fine sediment stored on this polygon.
Definition at line 671 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition(), CSimulation::WritePolygonPreExistingSedimentTable(), and CSimulation::WritePolygonSedimentBeforeMovement().
dGetPreExistingUnconsSand()
double CGeomCoastPolygon::dGetPreExistingUnconsSand (void) const
Get the value of pre-existing unconsolidated sand sediment stored on this polygon.
Definition at line 683 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), CSimulation::nDoAllActualBeachErosionAndDeposition(), CSimulation::WritePolygonPreExistingSedimentTable(), and CSimulation::WritePolygonSedimentBeforeMovement().
dGetSeawaterVolume()
double CGeomCoastPolygon::dGetSeawaterVolume (void) const
Get the volume of seawater in the coast polygon.
Definition at line 244 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonInfoTable().
dGetSedimentInputUnconsCoarse()
double CGeomCoastPolygon::dGetSedimentInputUnconsCoarse (void) const
Get the value of coarse sediment on the polygon derived from sediment input events(s)
Definition at line 767 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), CSimulation::WritePolygonPreExistingSedimentTable(), and CSimulation::WritePolygonSedimentInputEventTable().
dGetSedimentInputUnconsFine()
double CGeomCoastPolygon::dGetSedimentInputUnconsFine (void) const
Get the value of fine sediment on the polygon derived from sediment input events(s)
Definition at line 743 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), CSimulation::WritePolygonPreExistingSedimentTable(), and CSimulation::WritePolygonSedimentInputEventTable().
dGetSedimentInputUnconsSand()
double CGeomCoastPolygon::dGetSedimentInputUnconsSand (void) const
Get the value of sand sediment on the polygon derived from sediment input events(s)
Definition at line 755 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), CSimulation::WritePolygonPreExistingSedimentTable(), and CSimulation::WritePolygonSedimentInputEventTable().
dGetSuspensionUnconsFine()
double CGeomCoastPolygon::dGetSuspensionUnconsFine (void) const
Returns this timestep's to-suspension movement of fine unconsolidated sediment on this polygon, as a +ve depth in m.
Definition at line 316 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
dGetToDoBeachDepositionUnconsCoarse()
double CGeomCoastPolygon::dGetToDoBeachDepositionUnconsCoarse (void) const
Returns this timestep's still-to-do deposition of coarse unconsolidated sediment (from beach redistribution only) on this polygon, as a +ve depth in m.
Definition at line 376 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition(), and CSimulation::nDoUnconsDepositionOnPolygon().
dGetToDoBeachDepositionUnconsSand()
double CGeomCoastPolygon::dGetToDoBeachDepositionUnconsSand (void) const
Returns this timestep's still-to-do deposition of sand-sized unconsolidated sediment (from beach redistribution only) on this polygon, as a +ve depth in m.
Definition at line 358 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition(), and CSimulation::nDoUnconsDepositionOnPolygon().
dGetUpCoastAdjacentPolygonBoundaryShare()
double CGeomCoastPolygon::dGetUpCoastAdjacentPolygonBoundaryShare (int const nIndex) const
Gets the boundary shares for all up-coast adjacent polygons.
Definition at line 484 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
Display()
void CGeomCoastPolygon::Display (void) override virtual
Instantiates the pure virtual function in the abstract parent class, so that CGeomCoastPolygon is not an abstract class.
Implements CA2DShape.
Definition at line 516 of file coast_polygon.cpp.
nGetBoundarySize()
int CGeomCoastPolygon::nGetBoundarySize (void) const
Get the number of points in the polygon's boundary.
Definition at line 220 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
nGetDownCoastAdjacentPolygon()
int CGeomCoastPolygon::nGetDownCoastAdjacentPolygon (int const nIndex) const
Gets a single down-coast adjacent polygon.
Definition at line 437 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetDownCoastProfile()
int CGeomCoastPolygon::nGetDownCoastProfile (void) const
Return the number of the down-coast profile.
Definition at line 197 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion(), CSimulation::nDoPolygonSharedBoundaries(), CSimulation::nDoUnconsDepositionOnPolygon(), CSimulation::nDoUnconsErosionOnPolygon(), and CSimulation::WritePolygonInfoTable().
nGetNodeCoastPoint()
int CGeomCoastPolygon::nGetNodeCoastPoint (void) const
Get the coast node point.
Definition at line 149 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
nGetNumDownCoastAdjacentPolygons()
int CGeomCoastPolygon::nGetNumDownCoastAdjacentPolygons (void) const
Gets all down-coast adjacent polygons.
Definition at line 444 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetNumPointsUsedDownCoastProfile()
int CGeomCoastPolygon::nGetNumPointsUsedDownCoastProfile (void) const
Return the number of points in the down-coast profile.
Definition at line 232 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
nGetNumPointsUsedUpCoastProfile()
int CGeomCoastPolygon::nGetNumPointsUsedUpCoastProfile (void) const
Return the number of points in the up-coast profile.
Definition at line 226 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
nGetNumUpCoastAdjacentPolygons()
int CGeomCoastPolygon::nGetNumUpCoastAdjacentPolygons (void) const
Gets all up-coast adjacent polygons.
Definition at line 425 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetPolygonCoastID()
int CGeomCoastPolygon::nGetPolygonCoastID (void) const
Get the coast ID, this is the same as the down-coast sequence of polygons.
Definition at line 138 of file coast_polygon.cpp.
Referenced by CSimulation::CalcD50AndFillWaveCalcHoles(), CSimulation::MarkPolygonCells(), CSimulation::nDoAllActualBeachErosionAndDeposition(), CSimulation::nDoParallelProfileUnconsErosion(), CSimulation::nDoPolygonSharedBoundaries(), CSimulation::nDoUnconsDepositionOnPolygon(), CSimulation::nDoUnconsErosionOnPolygon(), CSimulation::WritePolygonCliffCollapseErosion(), CSimulation::WritePolygonInfoTable(), CSimulation::WritePolygonPotentialErosion(), CSimulation::WritePolygonPreExistingSedimentTable(), CSimulation::WritePolygonSedimentBeforeMovement(), CSimulation::WritePolygonSedimentInputEventTable(), CSimulation::WritePolygonShorePlatformErosion(), CSimulation::WritePolygonSortedSequence(), and CSimulation::WritePolygonUnsortedSequence().
nGetUpCoastAdjacentPolygon()
int CGeomCoastPolygon::nGetUpCoastAdjacentPolygon (int const nIndex) const
Gets a single up-coast adjacent polygon.
Definition at line 418 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
nGetUpCoastProfile()
int CGeomCoastPolygon::nGetUpCoastProfile (void) const
Return the number of the up-coast profile.
Definition at line 191 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion(), CSimulation::nDoPolygonSharedBoundaries(), CSimulation::nDoUnconsDepositionOnPolygon(), CSimulation::nDoUnconsErosionOnPolygon(), and CSimulation::WritePolygonInfoTable().
pPtGetBoundaryPoint()
CGeom2DPoint * CGeomCoastPolygon::pPtGetBoundaryPoint (int const nPoint)
Get the coordinates (external CRS) of a specified point on the polygon's boundary.
Definition at line 213 of file coast_polygon.cpp.
Referenced by CSimulation::bWriteVectorGISFile().
pPtiGetAntiNode()
CGeom2DIPoint * CGeomCoastPolygon::pPtiGetAntiNode (void)
Get the anti-node (raster grid CRS) which is at other (seaward) end of the polygon from the node.
Definition at line 161 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
pPtiGetNode()
CGeom2DIPoint * CGeomCoastPolygon::pPtiGetNode (void)
Get the grid coordinates of the cell on which the node sits.
Definition at line 155 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
PtiGetFillStartPoint()
CGeom2DIPoint CGeomCoastPolygon::PtiGetFillStartPoint (void)
Definition at line 791 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetAvgUnconsD50()
void CGeomCoastPolygon::SetAvgUnconsD50 (double const dD50)
Set the average d50 for unconsolidated sediment on this polygon.
Definition at line 504 of file coast_polygon.cpp.
Referenced by CSimulation::CalcD50AndFillWaveCalcHoles().
SetBeachDepositionUnconsCoarse()
void CGeomCoastPolygon::SetBeachDepositionUnconsCoarse (double const dDepth)
Sets the depth of coarse-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
Definition at line 334 of file coast_polygon.cpp.
Referenced by CSimulation::nDoUnconsDepositionOnPolygon().
SetBeachDepositionUnconsSand()
void CGeomCoastPolygon::SetBeachDepositionUnconsSand (double const dDepth)
Sets the depth of sand-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
Definition at line 322 of file coast_polygon.cpp.
Referenced by CSimulation::nDoUnconsDepositionOnPolygon().
SetBeachErosionUnconsCoarse()
void CGeomCoastPolygon::SetBeachErosionUnconsCoarse (double const dDepth)
Sets a value (must be < 0) for this timestep's erosion of coarse unconsolidated sediment (beach redistribution only) on this polygon. This includes coarse sediment eroded during Dean profile deposition of coarse sediment.
Definition at line 286 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
SetBeachErosionUnconsFine()
void CGeomCoastPolygon::SetBeachErosionUnconsFine (double const dDepth)
Sets a value (must be < 0) for this timestep's erosion of fine unconsolidated sediment (beach redistribution only) on this polygon.
Definition at line 262 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
SetBeachErosionUnconsSand()
void CGeomCoastPolygon::SetBeachErosionUnconsSand (double const dDepth)
Sets a value (must be < 0) for this timestep's erosion of sand-sized unconsolidated sediment (beach redistribution only) on this polygon. This includes sand sediment eroded during Dean profile deposition of sand sediment.
Definition at line 274 of file coast_polygon.cpp.
Referenced by CSimulation::nDoAllActualBeachErosionAndDeposition().
SetDownCoastAdjacentPolygonBoundaryShares()
void CGeomCoastPolygon::SetDownCoastAdjacentPolygonBoundaryShares (vector< double > const * pdVShares)
Sets the boundary shares for all down-coast adjacent polygons.
Definition at line 491 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetDownCoastAdjacentPolygons()
void CGeomCoastPolygon::SetDownCoastAdjacentPolygons (vector< int > const * pnVPolygons)
Sets all down-coast adjacent polygons.
Definition at line 431 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetDownCoastThisIter()
void CGeomCoastPolygon::SetDownCoastThisIter (bool const bFlag)
Set a flag to say whether sediment movement on this polygon is down-coast this iteration.
Definition at line 102 of file coast_polygon.cpp.
Referenced by CSimulation::DoAllPotentialBeachErosion().
SetLength()
void CGeomCoastPolygon::SetLength (double const dLength)
Sets the polygon's length.
Definition at line 167 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetNumCellsInPolygon()
void CGeomCoastPolygon::SetNumCellsInPolygon (int const nCells)
Set the number of cells in the polygon.
Definition at line 179 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetPreExistingConsCoarse()
void CGeomCoastPolygon::SetPreExistingConsCoarse (double const dDepth)
Set the value of pre-existing consolidated coarse sediment stored on this polygon.
Definition at line 725 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetPreExistingConsFine()
void CGeomCoastPolygon::SetPreExistingConsFine (double const dDepth)
Set the value of pre-existing consolidated fine sediment stored on this polygon.
Definition at line 701 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetPreExistingConsSand()
void CGeomCoastPolygon::SetPreExistingConsSand (double const dDepth)
Set the value of pre-existing consolidated sand sediment stored on this polygon.
Definition at line 713 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetPreExistingUnconsCoarse()
void CGeomCoastPolygon::SetPreExistingUnconsCoarse (double const dDepth)
Set the value of pre-existing unconsolidated coarse sediment stored on this polygon.
Definition at line 689 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::MarkPolygonCells().
SetPreExistingUnconsFine()
void CGeomCoastPolygon::SetPreExistingUnconsFine (double const dDepth)
Set the value of pre-existing unconsolidated fine sediment stored on this polygon.
Definition at line 665 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::MarkPolygonCells().
SetPreExistingUnconsSand()
void CGeomCoastPolygon::SetPreExistingUnconsSand (double const dDepth)
Set the value of pre-existing unconsolidated sand sediment stored on this polygon.
Definition at line 677 of file coast_polygon.cpp.
Referenced by CSimulation::AllPolygonsUpdateStoredUncons(), and CSimulation::MarkPolygonCells().
SetSeawaterVolume()
void CGeomCoastPolygon::SetSeawaterVolume (const double dDepth)
Set the volume of seawater in the coast polygon.
Definition at line 238 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetSedimentInputUnconsCoarse()
void CGeomCoastPolygon::SetSedimentInputUnconsCoarse (double const dDepth)
Set the value of coarse sediment on the polygon derived from sediment input events(s)
Definition at line 761 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetSedimentInputUnconsFine()
void CGeomCoastPolygon::SetSedimentInputUnconsFine (double const dDepth)
Set the value of fine sediment on the polygon derived from sediment input events(s)
Definition at line 737 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetSedimentInputUnconsSand()
void CGeomCoastPolygon::SetSedimentInputUnconsSand (double const dDepth)
Set the value of sand sediment on the polygon derived from sediment input events(s)
Definition at line 749 of file coast_polygon.cpp.
Referenced by CSimulation::MarkPolygonCells().
SetUpCoastAdjacentPolygonBoundaryShares()
void CGeomCoastPolygon::SetUpCoastAdjacentPolygonBoundaryShares (vector< double > const * pdVShares)
Sets the boundary shares for all up-coast adjacent polygons.
Definition at line 478 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetUpCoastAdjacentPolygons()
void CGeomCoastPolygon::SetUpCoastAdjacentPolygons (vector< int > const * pnVPolygons)
Sets all up-coast adjacent polygons.
Definition at line 412 of file coast_polygon.cpp.
Referenced by CSimulation::nDoPolygonSharedBoundaries().
SetZeroToDoDepositionUnconsCoarse()
void CGeomCoastPolygon::SetZeroToDoDepositionUnconsCoarse (void)
Re-initialises this timestep's still-to-do deposition of unconsolidated coarse sediment (from beach redistribution only) on this polygon.
Definition at line 364 of file coast_polygon.cpp.
Referenced by CSimulation::nDoUnconsDepositionOnPolygon().
SetZeroToDoDepositionUnconsSand()
void CGeomCoastPolygon::SetZeroToDoDepositionUnconsSand (void)
Re-initialises this timestep's still-to-do deposition of unconsolidated sand sediment (from beach redistribution only) on this polygon.
Definition at line 346 of file coast_polygon.cpp.
Referenced by CSimulation::nDoUnconsDepositionOnPolygon().
VnGetCircularities()
vector< int > const * CGeomCoastPolygon::VnGetCircularities (void) const
Get all circularities for this polygon.
Definition at line 527 of file coast_polygon.cpp.
Referenced by CSimulation::WritePolygonSortedSequence().
Field Documentation
m_bCoastEndPolygon
bool CGeomCoastPolygon::m_bCoastEndPolygon private
Is this polygon at the end of the coastline?
Definition at line 39 of file coast_polygon.h.
Referenced by bIsCoastEndPolygon(), and CGeomCoastPolygon().
m_bCoastStartPolygon
bool CGeomCoastPolygon::m_bCoastStartPolygon private
Is this polygon at the start of the coastline?
Definition at line 42 of file coast_polygon.h.
Referenced by bIsCoastStartPolygon(), and CGeomCoastPolygon().
m_bUnconsSedimentMovementDownCoastThisIter
bool CGeomCoastPolygon::m_bUnconsSedimentMovementDownCoastThisIter private
Is the movement of unconsolidated sediment on this polygon down-coast (i.e. along the coast in the direction of increasing coastline point numbers) during this iteration?
Definition at line 33 of file coast_polygon.h.
Referenced by bDownCoastThisIter(), CGeomCoastPolygon(), and SetDownCoastThisIter().
m_dAvgUnconsD50
double CGeomCoastPolygon::m_dAvgUnconsD50 private
The average d50 of unconsolidated sediment on this polygon.
Definition at line 66 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetAvgUnconsD50(), and SetAvgUnconsD50().
m_dBeachCoarseErodedDeanProfile
double CGeomCoastPolygon::m_dBeachCoarseErodedDeanProfile private
Depth of coarse unconsolidated sediment eroded during beach deposition as a Dean profile.
Definition at line 104 of file coast_polygon.h.
Referenced by AddBeachCoarseErodedDeanProfile(), CGeomCoastPolygon(), and dGetBeachCoarseErodedDeanProfile().
m_dBeachDepositionUnconsCoarse
double CGeomCoastPolygon::m_dBeachDepositionUnconsCoarse private
Depth of coarse-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
Definition at line 89 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetBeachDepositionUnconsCoarse(), and SetBeachDepositionUnconsCoarse().
m_dBeachDepositionUnconsSand
double CGeomCoastPolygon::m_dBeachDepositionUnconsSand private
Depth of sand-sized unconsolidated sediment deposited on this polygon during this timestep (+ve, beach redistribution only)
Definition at line 86 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetBeachDepositionUnconsSand(), and SetBeachDepositionUnconsSand().
m_dBeachErosionUnconsCoarse
double CGeomCoastPolygon::m_dBeachErosionUnconsCoarse private
Erosion (considering supply-limitation) of coarse-sized unconsolidated sediment as a depth this timestep (-ve), beach redistribution only. This includes coarse sediment eroded during Dean profile deposition of coarse sediment.
Definition at line 83 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGeBeachErosionAllUncons(), dGetBeachErosionUnconsCoarse(), and SetBeachErosionUnconsCoarse().
m_dBeachErosionUnconsFine
double CGeomCoastPolygon::m_dBeachErosionUnconsFine private
Erosion (considering supply-limitation) of fine-sized unconsolidated sediment as a depth this timestep (-ve), beach redistribution only.
Definition at line 77 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGeBeachErosionAllUncons(), dGetBeachErosionUnconsFine(), and SetBeachErosionUnconsFine().
m_dBeachErosionUnconsSand
double CGeomCoastPolygon::m_dBeachErosionUnconsSand private
Erosion (considering supply-limitation) of sand-sized unconsolidated sediment as a depth this timestep (-ve), beach redistribution only. This includes sand sediment eroded during Dean profile deposition of sand sediment.
Definition at line 80 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGeBeachErosionAllUncons(), dGetBeachErosionUnconsSand(), and SetBeachErosionUnconsSand().
m_dBeachSandErodedDeanProfile
double CGeomCoastPolygon::m_dBeachSandErodedDeanProfile private
Depth of sand unconsolidated sediment eroded during beach deposition as a Dean profile.
Definition at line 101 of file coast_polygon.h.
Referenced by AddBeachSandErodedDeanProfile(), CGeomCoastPolygon(), and dGetBeachSandErodedDeanProfile().
m_dCliffCollapseCoarseErodedDeanProfile
double CGeomCoastPolygon::m_dCliffCollapseCoarseErodedDeanProfile private
Depth of coarse unconsolidated sediment eroded during deposition of cliff collapse talus as a Dean profile.
Definition at line 128 of file coast_polygon.h.
Referenced by AddCliffCollapseCoarseErodedDeanProfile(), CGeomCoastPolygon(), and dGetCliffCollapseCoarseErodedDeanProfile().
m_dCliffCollapseErosionCoarse
double CGeomCoastPolygon::m_dCliffCollapseErosionCoarse private
Depth of eroded coarse sediment from cliff collapse, note that this does not include coarse sediment eroded during Dean profile deposition of talus.
Definition at line 113 of file coast_polygon.h.
Referenced by AddCliffCollapseErosionCoarse(), CGeomCoastPolygon(), and dGetCliffCollapseErosionCoarse().
m_dCliffCollapseErosionFine
double CGeomCoastPolygon::m_dCliffCollapseErosionFine private
Depth of eroded fine sediment from cliff collapse (is always equal to m_dCliffCollapseToSuspensionFine)
Definition at line 107 of file coast_polygon.h.
Referenced by AddCliffCollapseErosionFine(), CGeomCoastPolygon(), and dGetCliffCollapseErosionFine().
m_dCliffCollapseErosionSand
double CGeomCoastPolygon::m_dCliffCollapseErosionSand private
Depth of eroded sand sediment from cliff collapse, note that this does not include sand sediment eroded during Dean profile deposition of talus.
Definition at line 110 of file coast_polygon.h.
Referenced by AddCliffCollapseErosionSand(), CGeomCoastPolygon(), and dGetCliffCollapseErosionSand().
m_dCliffCollapseSandErodedDeanProfile
double CGeomCoastPolygon::m_dCliffCollapseSandErodedDeanProfile private
Depth of sand unconsolidated sediment eroded during deposition of cliff collapse talus as a Dean profile.
Definition at line 125 of file coast_polygon.h.
Referenced by AddCliffCollapseSandErodedDeanProfile(), CGeomCoastPolygon(), and dGetCliffCollapseSandErodedDeanProfile().
m_dCliffCollapseTalusCoarse
double CGeomCoastPolygon::m_dCliffCollapseTalusCoarse private
Depth of unconsolidated coarse talus from cliff collapse.
Definition at line 122 of file coast_polygon.h.
Referenced by AddCliffCollapseUnconsCoarseDeposition(), CGeomCoastPolygon(), and dGetCliffCollapseUnconsCoarseDeposition().
m_dCliffCollapseTalusFineToSuspension
double CGeomCoastPolygon::m_dCliffCollapseTalusFineToSuspension private
Depth of unconsolidated fine sediment which goes to suspension from cliff collapse.
Definition at line 116 of file coast_polygon.h.
Referenced by AddCliffCollapseToSuspensionFine(), CGeomCoastPolygon(), and dGetCliffCollapseToSuspensionFine().
m_dCliffCollapseTalusSand
double CGeomCoastPolygon::m_dCliffCollapseTalusSand private
Depth of unconsolidated sand talus from cliff collapse.
Definition at line 119 of file coast_polygon.h.
Referenced by AddCliffCollapseUnconsSandDeposition(), CGeomCoastPolygon(), and dGetCliffCollapseUnconsSandDeposition().
m_dLength
double CGeomCoastPolygon::m_dLength private
Coast polygon length.
Definition at line 167 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetLength(), and SetLength().
m_dPlatformErosionToSuspensionFine
double CGeomCoastPolygon::m_dPlatformErosionToSuspensionFine private
Depth of fine sediment moved to suspension from shore platform erosion.
Definition at line 131 of file coast_polygon.h.
Referenced by CGeomCoastPolygon().
m_dPlatformErosionUnconsCoarse
double CGeomCoastPolygon::m_dPlatformErosionUnconsCoarse private
Depth of unconsolidated coarse sediment from shore platform erosion.
Definition at line 137 of file coast_polygon.h.
Referenced by AddPlatformErosionUnconsCoarse(), CGeomCoastPolygon(), and dGetPlatformErosionUnconsCoarse().
m_dPlatformErosionUnconsSand
double CGeomCoastPolygon::m_dPlatformErosionUnconsSand private
Depth of unconsolidated sand sediment from shore platform erosion.
Definition at line 134 of file coast_polygon.h.
Referenced by AddPlatformErosionUnconsSand(), CGeomCoastPolygon(), and dGetPlatformErosionUnconsSand().
m_dPotentialBeachErosionAllUncons
double CGeomCoastPolygon::m_dPotentialBeachErosionAllUncons private
Potential (ignoring supply-limitation) erosion of unconsolidated sediment (all size classes) as a depth during this timestep (-ve), beach redistribution only.
Definition at line 74 of file coast_polygon.h.
Referenced by AddPotentialErosion(), CGeomCoastPolygon(), and dGetPotentialErosion().
m_dPreExistingConsCoarse
double CGeomCoastPolygon::m_dPreExistingConsCoarse private
Depth of pre-existing consolidated coarse sediment.
Definition at line 155 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetPreExistingConsCoarse(), and SetPreExistingConsCoarse().
m_dPreExistingConsFine
double CGeomCoastPolygon::m_dPreExistingConsFine private
Depth of pre-existing consolidated fine sediment.
Definition at line 149 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetPreExistingConsFine(), and SetPreExistingConsFine().
m_dPreExistingConsSand
double CGeomCoastPolygon::m_dPreExistingConsSand private
Depth of pre-existing consolidated sand sediment.
Definition at line 152 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetPreExistingConsSand(), and SetPreExistingConsSand().
m_dPreExistingUnconsCoarse
double CGeomCoastPolygon::m_dPreExistingUnconsCoarse private
Depth of pre-existing unconsolidated coarse sedimet.
Definition at line 146 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetPreExistingUnconsCoarse(), and SetPreExistingUnconsCoarse().
m_dPreExistingUnconsFine
double CGeomCoastPolygon::m_dPreExistingUnconsFine private
Depth of pre-existing unconsolidated fine sediment.
Definition at line 140 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetPreExistingUnconsFine(), and SetPreExistingUnconsFine().
m_dPreExistingUnconsSand
double CGeomCoastPolygon::m_dPreExistingUnconsSand private
Depth of pre-existing unconsolidated sand sediment.
Definition at line 143 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetPreExistingUnconsSand(), and SetPreExistingUnconsSand().
m_dSeawaterVolume
double CGeomCoastPolygon::m_dSeawaterVolume private
The volume (m3) of sea water within the polygon.
Definition at line 69 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetSeawaterVolume(), and SetSeawaterVolume().
m_dSedimentInputCoarse
double CGeomCoastPolygon::m_dSedimentInputCoarse private
Depth of coarse sediment added from this-iteration sediment input event(s)
Definition at line 164 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetSedimentInputUnconsCoarse(), and SetSedimentInputUnconsCoarse().
m_dSedimentInputFine
double CGeomCoastPolygon::m_dSedimentInputFine private
Depth of fine sediment added from this-iteration sediment input event(s)
Definition at line 158 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetSedimentInputUnconsFine(), and SetSedimentInputUnconsFine().
m_dSedimentInputSand
double CGeomCoastPolygon::m_dSedimentInputSand private
Depth of sand sediment added from this-iteration sediment input event(s)
Definition at line 161 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetSedimentInputUnconsSand(), and SetSedimentInputUnconsSand().
m_dSuspensionUnconsFine
double CGeomCoastPolygon::m_dSuspensionUnconsFine private
To-suspension movement of fine-sized sediment as a depth this timestep (+ve) ALL PROCESSES TODO *** CHECK *** REPLACE, INSTEAD USE TOTALS FROM TO-SUSPENSION FINE FROM (a) PLATFORM EROSION (b) CLIFF COLLAPSE (c) BEACH EROSION.
Definition at line 92 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), dGetBeachDepositionAndSuspensionAllUncons(), and dGetSuspensionUnconsFine().
m_dToDoBeachDepositionUnconsCoarse
double CGeomCoastPolygon::m_dToDoBeachDepositionUnconsCoarse private
Still-to-do depth (m) of coarse-sized unconsolidated sediment to be deposited this timestep (+ve), beach redistribution only.
Definition at line 98 of file coast_polygon.h.
Referenced by AddToDoBeachDepositionUnconsCoarse(), CGeomCoastPolygon(), dGetBeachDepositionAndSuspensionAllUncons(), dGetToDoBeachDepositionUnconsCoarse(), and SetZeroToDoDepositionUnconsCoarse().
m_dToDoBeachDepositionUnconsSand
double CGeomCoastPolygon::m_dToDoBeachDepositionUnconsSand private
Still-to-do depth (m) of sand-sized unconsolidated sediment to be deposited this timestep (+ve), beach redistribution only.
Definition at line 95 of file coast_polygon.h.
Referenced by AddToDoBeachDepositionUnconsSand(), CGeomCoastPolygon(), dGetBeachDepositionAndSuspensionAllUncons(), dGetToDoBeachDepositionUnconsSand(), and SetZeroToDoDepositionUnconsSand().
m_nCoastID
int CGeomCoastPolygon::m_nCoastID private
This-coast-only number of this polygon.
Definition at line 45 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and nGetPolygonCoastID().
m_nCoastNode
int CGeomCoastPolygon::m_nCoastNode private
The point on this polygon's coastline segment with maximum concave curvature, roughly at the middle of the coastline segment.
Definition at line 48 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and nGetNodeCoastPoint().
m_nNumCells
int CGeomCoastPolygon::m_nNumCells private
The number of cells in the polygon.
Definition at line 63 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and SetNumCellsInPolygon().
m_nProfileDownCoast
int CGeomCoastPolygon::m_nProfileDownCoast private
The normal profile which bounds the polygon in the down-coast direction.
Definition at line 54 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and nGetDownCoastProfile().
m_nProfileDownCoastNumPointsUsed
int CGeomCoastPolygon::m_nProfileDownCoastNumPointsUsed private
The number of points from the down-coast normal which are part of this polygon (less than the normal's full length if the polygon is triangular)
Definition at line 60 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and nGetNumPointsUsedDownCoastProfile().
m_nProfileUpCoast
int CGeomCoastPolygon::m_nProfileUpCoast private
The normal profile which bounds the polygon in the up-coast direction.
Definition at line 51 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and nGetUpCoastProfile().
m_nProfileUpCoastNumPointsUsed
int CGeomCoastPolygon::m_nProfileUpCoastNumPointsUsed private
The number of points from the up-coast normal which are part of this polygon (less than the normal's full length if the polygon is triangular)
Definition at line 57 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and nGetNumPointsUsedUpCoastProfile().
m_PtiAntinode
CGeom2DIPoint CGeomCoastPolygon::m_PtiAntinode private
Coordinates of the cell (raster grid CRS) which is at other (seaward) end of the polygon.
Definition at line 173 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and pPtiGetAntiNode().
m_PtiNode
CGeom2DIPoint CGeomCoastPolygon::m_PtiNode private
Coordinates of the coast node cell (raster grid CRS)
Definition at line 170 of file coast_polygon.h.
Referenced by CGeomCoastPolygon(), and pPtiGetNode().
m_VdDownCoastAdjacentPolygonBoundaryShare
vector<double> CGeomCoastPolygon::m_VdDownCoastAdjacentPolygonBoundaryShare private
The boundary share(s) (0 to 1) with adjacent up-coast polygon(s)
Definition at line 188 of file coast_polygon.h.
Referenced by dGetDownCoastAdjacentPolygonBoundaryShare(), and SetDownCoastAdjacentPolygonBoundaryShares().
m_VdUpCoastAdjacentPolygonBoundaryShare
vector<double> CGeomCoastPolygon::m_VdUpCoastAdjacentPolygonBoundaryShare private
The boundary share(s) (0 to 1) with adjacent up-coast polygon(s)
Definition at line 185 of file coast_polygon.h.
Referenced by dGetUpCoastAdjacentPolygonBoundaryShare(), and SetUpCoastAdjacentPolygonBoundaryShares().
m_VnCircularityWith
vector<int> CGeomCoastPolygon::m_VnCircularityWith private
If this polygon has a circular unconsolidated-sediment-movement relationship with one or more other polygons, the coast-only numbers of these polygons.
Definition at line 182 of file coast_polygon.h.
Referenced by AddCircularity(), and VnGetCircularities().
m_VnDownCoastAdjacentPolygon
vector<int> CGeomCoastPolygon::m_VnDownCoastAdjacentPolygon private
The ID(s) of the down-coast adjacent polygon(s)
Definition at line 179 of file coast_polygon.h.
Referenced by bDownCoastIsAlreadyPresent(), nGetDownCoastAdjacentPolygon(), nGetNumDownCoastAdjacentPolygons(), and SetDownCoastAdjacentPolygons().
m_VnUpCoastAdjacentPolygon
vector<int> CGeomCoastPolygon::m_VnUpCoastAdjacentPolygon private
The ID(s) of the up-coast adjacent polygon(s)
Definition at line 176 of file coast_polygon.h.
Referenced by bUpCoastIsAlreadyPresent(), nGetNumUpCoastAdjacentPolygons(), nGetUpCoastAdjacentPolygon(), and SetUpCoastAdjacentPolygons().
m_VPtiVertices
vector<CGeom2DIPoint> CGeomCoastPolygon::m_VPtiVertices private
The polygon's vertices (not all of them, just the ends of the profile sides), used to calculate the polygon's centroid for filling it.
Definition at line 191 of file coast_polygon.h.
Referenced by AppendVertex(), and PtiGetFillStartPoint().
The documentation for this class was generated from the following files:
coast_polygon.h
coast_polygon.cpp