CoastalME (Coastal Modelling Environment): Load/save auxiliary functions
Load/save auxiliary functions
nanoflann C++ library for KD-trees
Functions
template<typename T>
void nanoflann::save_value (std::ostream &stream, const T &value)
template<typename T>
void nanoflann::save_value (std::ostream &stream, const std::vector< T > &value)
template<typename T>
void nanoflann::load_value (std::istream &stream, T &value)
template<typename T>
void nanoflann::load_value (std::istream &stream, std::vector< T > &value)
Detailed Description
Function Documentation
load_value() [1/2]
template<typename T> void nanoflann::load_value (std::istream & stream, std::vector< T > & value)
Definition at line 470 of file nanoflann.hpp.
load_value() [2/2]
template<typename T> void nanoflann::load_value (std::istream & stream, T & value)
Definition at line 464 of file nanoflann.hpp.
Referenced by nanoflann::KDTreeBaseClass< Derived, Distance, DatasetAdaptor, DIM, index_t >::load_tree(), load_value(), load_value(), and nanoflann::KDTreeBaseClass< Derived, Distance, DatasetAdaptor, DIM, index_t >::loadIndex().
save_value() [1/2]
template<typename T> void nanoflann::save_value (std::ostream & stream, const std::vector< T > & value)
Definition at line 456 of file nanoflann.hpp.
save_value() [2/2]
template<typename T> void nanoflann::save_value (std::ostream & stream, const T & value)
Definition at line 450 of file nanoflann.hpp.
Referenced by nanoflann::KDTreeBaseClass< Derived, Distance, DatasetAdaptor, DIM, index_t >::save_tree(), save_value(), save_value(), and nanoflann::KDTreeBaseClass< Derived, Distance, DatasetAdaptor, DIM, index_t >::saveIndex().