CoastalME (Coastal Modelling Environment): CRWCellLandform Class Reference
CRWCellLandform Class Reference
Real-world class used to represent the landform of a cell.
#include <cell_landform.h>
Public Member Functions
CRWCellLandform ()
Constructor.
~CRWCellLandform (void)
Destructor.
void SetLFCategory (int const)
Set the landform category.
int nGetLFCategory (void) const
Get the landform category.
void SetCoast (int const)
Set the coast number.
int nGetCoast (void) const
Get the coast number.
void SetPointOnCoast (int const)
Set the number of the point on the coastline.
int nGetPointOnCoast (void) const
Set the number of the point on the coastline.
void SetAccumWaveEnergy (double const)
Set accumulated wave energy.
void AddToAccumWaveEnergy (double const)
Add to acccumulated wave energy.
double dGetAccumWaveEnergy (void) const
Get accumulated wave energy.
void SetCliffNotchApexElev (double const)
Set cliff notch apex elevation.
double dGetCliffNotchApexElev (void) const
Get cliff notch apex elevation: this is the elevation of the most deeply incised horizontal plane within the notch, see Figure 3 in Trenhaile, A.S. (2015). Coastal notches: Their morphology, formation, and function. Earth-Science Reviews 150, 285-304. In CoastalME, where the notch is assumed to have the same depth of incision on all horizonal planes within the notch, the apex is assumed to be the vertical mid-point between the upper and lower edges of the notch.
void SetCliffNotchIncisionDepth (double const)
Set the horizontal depth of cliff notch incision for this cell. This is the horizontal distance from the edge of the cell to the incised back of the notch.
void AddToCliffNotchIncisionDepth (double const)
Adds to the horizontal depth of cliff notch incision for this cell. This is the horizontal distance from the edge of the cell to the incised back of the notch.
double dGetCliffNotchIncisionDepth (void) const
Get the horizontal depth of cliff notch incision for this cell. This is the horizontal distance from the edge of the cell to the incised back of the notch.
Private Attributes
int m_nCategory
Landform category for this cell.
int m_nCoast
Coast on which this landform sits (if any)
int m_nPointOnCoastline
Point on coast on which this landform sits (if any)
double m_dAccumWaveEnergy
Accumulate wave energy for this landform on this cell.
union {
struct {
int m_nDummy
Currently unused for all landforms except cliffs.
} m_sBeachData
struct {
double m_dNotchApexElev
Cliff notch base elevation.
double m_dNotchIncision
Cliff notch, horizontal depth of incision.
} m_sCliffData
} m_uLFData
The m_uLFData will hold landform data: currently, only cliffs are considered.
Detailed Description
Real-world class used to represent the landform of a cell.
TODO 001 This is a more detailed description of the CCRWCellLandform class.
Author
David Favis-Mortlock
Andres Payo
Date
2025
Copyright
GNU General Public License
Definition at line 24 of file cell_landform.h.
Constructor & Destructor Documentation
CRWCellLandform()
CRWCellLandform::CRWCellLandform ()
Constructor.
Definition at line 24 of file cell_landform.cpp.
~CRWCellLandform()
CRWCellLandform::~CRWCellLandform (void)
Destructor.
Definition at line 38 of file cell_landform.cpp.
Member Function Documentation
AddToAccumWaveEnergy()
void CRWCellLandform::AddToAccumWaveEnergy (double const dEnergyIn)
Add to acccumulated wave energy.
Definition at line 85 of file cell_landform.cpp.
AddToCliffNotchIncisionDepth()
void CRWCellLandform::AddToCliffNotchIncisionDepth (double const dLenIn)
Adds to the horizontal depth of cliff notch incision for this cell. This is the horizontal distance from the edge of the cell to the incised back of the notch.
Definition at line 115 of file cell_landform.cpp.
dGetAccumWaveEnergy()
double CRWCellLandform::dGetAccumWaveEnergy (void) const
Get accumulated wave energy.
Definition at line 91 of file cell_landform.cpp.
dGetCliffNotchApexElev()
double CRWCellLandform::dGetCliffNotchApexElev (void) const
Get cliff notch apex elevation: this is the elevation of the most deeply incised horizontal plane within the notch, see Figure 3 in Trenhaile, A.S. (2015). Coastal notches: Their morphology, formation, and function. Earth-Science Reviews 150, 285-304. In CoastalME, where the notch is assumed to have the same depth of incision on all horizonal planes within the notch, the apex is assumed to be the vertical mid-point between the upper and lower edges of the notch.
Definition at line 103 of file cell_landform.cpp.
dGetCliffNotchIncisionDepth()
double CRWCellLandform::dGetCliffNotchIncisionDepth (void) const
Get the horizontal depth of cliff notch incision for this cell. This is the horizontal distance from the edge of the cell to the incised back of the notch.
Definition at line 121 of file cell_landform.cpp.
nGetCoast()
int CRWCellLandform::nGetCoast (void) const
Get the coast number.
Definition at line 61 of file cell_landform.cpp.
nGetLFCategory()
int CRWCellLandform::nGetLFCategory (void) const
Get the landform category.
Definition at line 49 of file cell_landform.cpp.
Referenced by CSimulation::bElevAboveDeanElev(), CSimulation::bSurroundedByDriftCells(), CSimulation::CellByCellFillSea(), CSimulation::nAssignLandformsForAllCells(), CSimulation::nDoParallelProfileUnconsErosion(), and CSimulation::nDoUnconsDepositionOnPolygon().
nGetPointOnCoast()
int CRWCellLandform::nGetPointOnCoast (void) const
Set the number of the point on the coastline.
Definition at line 73 of file cell_landform.cpp.
SetAccumWaveEnergy()
void CRWCellLandform::SetAccumWaveEnergy (double const dEnergyIn)
Set accumulated wave energy.
Definition at line 79 of file cell_landform.cpp.
SetCliffNotchApexElev()
void CRWCellLandform::SetCliffNotchApexElev (double const dElevIn)
Set cliff notch apex elevation.
Definition at line 97 of file cell_landform.cpp.
SetCliffNotchIncisionDepth()
void CRWCellLandform::SetCliffNotchIncisionDepth (double const dLenIn)
Set the horizontal depth of cliff notch incision for this cell. This is the horizontal distance from the edge of the cell to the incised back of the notch.
Definition at line 109 of file cell_landform.cpp.
SetCoast()
void CRWCellLandform::SetCoast (int const nCoastIn)
Set the coast number.
Definition at line 55 of file cell_landform.cpp.
SetLFCategory()
void CRWCellLandform::SetLFCategory (int const nClassIn)
Set the landform category.
Definition at line 43 of file cell_landform.cpp.
Referenced by CSimulation::CellByCellFillSea(), CSimulation::nAssignLandformsForAllCells(), CSimulation::nDoParallelProfileUnconsErosion(), CSimulation::nDoSedimentInputEvent(), and CSimulation::nDoUnconsDepositionOnPolygon().
SetPointOnCoast()
void CRWCellLandform::SetPointOnCoast (int const nPointOnCoastIn)
Set the number of the point on the coastline.
Definition at line 67 of file cell_landform.cpp.
Field Documentation
m_dAccumWaveEnergy
double CRWCellLandform::m_dAccumWaveEnergy private
Accumulate wave energy for this landform on this cell.
Definition at line 37 of file cell_landform.h.
Referenced by AddToAccumWaveEnergy(), CRWCellLandform(), dGetAccumWaveEnergy(), and SetAccumWaveEnergy().
m_dNotchApexElev
double CRWCellLandform::m_dNotchApexElev
Cliff notch base elevation.
Definition at line 51 of file cell_landform.h.
m_dNotchIncision
double CRWCellLandform::m_dNotchIncision
Cliff notch, horizontal depth of incision.
Definition at line 54 of file cell_landform.h.
m_nCategory
int CRWCellLandform::m_nCategory private
Landform category for this cell.
Definition at line 28 of file cell_landform.h.
Referenced by CRWCellLandform(), nGetLFCategory(), and SetLFCategory().
m_nCoast
int CRWCellLandform::m_nCoast private
Coast on which this landform sits (if any)
Definition at line 31 of file cell_landform.h.
Referenced by CRWCellLandform(), nGetCoast(), and SetCoast().
m_nDummy
int CRWCellLandform::m_nDummy
Currently unused for all landforms except cliffs.
Definition at line 45 of file cell_landform.h.
m_nPointOnCoastline
int CRWCellLandform::m_nPointOnCoastline private
Point on coast on which this landform sits (if any)
Definition at line 34 of file cell_landform.h.
Referenced by CRWCellLandform(), nGetPointOnCoast(), and SetPointOnCoast().
[struct]
struct { ... } CRWCellLandform::m_sBeachData
[struct]
struct { ... } CRWCellLandform::m_sCliffData
[union]
union { ... } CRWCellLandform::m_uLFData
The m_uLFData will hold landform data: currently, only cliffs are considered.
Referenced by AddToCliffNotchIncisionDepth(), CRWCellLandform(), dGetCliffNotchApexElev(), dGetCliffNotchIncisionDepth(), SetCliffNotchApexElev(), and SetCliffNotchIncisionDepth().
The documentation for this class was generated from the following files:
cell_landform.h
cell_landform.cpp