CoastalME (Coastal Modelling Environment): CRWCellLayer Class Reference
CRWCellLayer Class Reference
Real-world class used to represent the sediment layers associated with a cell object.
#include <cell_layer.h>
Public Member Functions
CRWCellLayer (void)
Constructor.
CRWCellSediment * pGetUnconsolidatedSediment (void)
Returns a pointer to the cell's unconsolidated sediment object.
CRWCellSediment * pGetConsolidatedSediment (void)
Returns a pointer to the cell's consolidated sediment object.
double dGetFineUnconsolidatedThickness (void) const
Returns the thickness of this cell's fine unconsolidated sediment.
double dGetFineConsolidatedThickness (void) const
Returns the thickness of this cell's fine consolidated sediment.
double dGetSandUnconsolidatedThickness (void) const
Returns the thickness of this cell's sand unconsolidated sediment.
double dGetSandConsolidatedThickness (void) const
Returns the thickness of this cell's sand consolidated sediment.
double dGetCoarseUnconsolidatedThickness (void) const
Returns the thickness of this cell's coarse unconsolidated sediment.
double dGetCoarseConsolidatedThickness (void) const
Returns the thickness of this cell's coarse consolidated sediment.
double dGetUnconsolidatedThickness (void) const
Returns the thickness of this cell's unconsolidated sediment (total for all size classes)
double dGetConsolidatedThickness (void) const
Returns the thickness of this cell's consolidated sediment (total for all size classes)
double dGetTotalThickness (void) const
Returns the thickness of this cell's sediment (total for all size classes, both consolidated and unconsolidated)
void SetVolSedFraction (double const)
Private Attributes
CRWCellSediment m_UnconsolidatedSediment
This cell's unconsolidated sediment object.
CRWCellSediment m_ConsolidatedSediment
This cell's consolidated sediment object.
Detailed Description
Real-world class used to represent the sediment layers associated with a cell object.
TODO 001 This is a more detailed description of the CCRWCellLayer class.
Author
David Favis-Mortlock
Andres Payo
Date
2025
Copyright
GNU General Public License
Definition at line 31 of file cell_layer.h.
Constructor & Destructor Documentation
CRWCellLayer()
CRWCellLayer::CRWCellLayer (void)
Constructor.
Definition at line 30 of file cell_layer.cpp.
Member Function Documentation
dGetCoarseConsolidatedThickness()
double CRWCellLayer::dGetCoarseConsolidatedThickness (void) const
Returns the thickness of this cell's coarse consolidated sediment.
Definition at line 77 of file cell_layer.cpp.
Referenced by CGeomCell::dGetTotConsCoarseThickConsiderNotch().
dGetCoarseUnconsolidatedThickness()
double CRWCellLayer::dGetCoarseUnconsolidatedThickness (void) const
Returns the thickness of this cell's coarse unconsolidated sediment.
Definition at line 71 of file cell_layer.cpp.
dGetConsolidatedThickness()
double CRWCellLayer::dGetConsolidatedThickness (void) const
Returns the thickness of this cell's consolidated sediment (total for all size classes)
Definition at line 89 of file cell_layer.cpp.
dGetFineConsolidatedThickness()
double CRWCellLayer::dGetFineConsolidatedThickness (void) const
Returns the thickness of this cell's fine consolidated sediment.
Definition at line 53 of file cell_layer.cpp.
Referenced by CGeomCell::dGetTotConsFineThickConsiderNotch().
dGetFineUnconsolidatedThickness()
double CRWCellLayer::dGetFineUnconsolidatedThickness (void) const
Returns the thickness of this cell's fine unconsolidated sediment.
Definition at line 47 of file cell_layer.cpp.
dGetSandConsolidatedThickness()
double CRWCellLayer::dGetSandConsolidatedThickness (void) const
Returns the thickness of this cell's sand consolidated sediment.
Definition at line 65 of file cell_layer.cpp.
Referenced by CGeomCell::dGetTotConsSandThickConsiderNotch().
dGetSandUnconsolidatedThickness()
double CRWCellLayer::dGetSandUnconsolidatedThickness (void) const
Returns the thickness of this cell's sand unconsolidated sediment.
Definition at line 59 of file cell_layer.cpp.
dGetTotalThickness()
double CRWCellLayer::dGetTotalThickness (void) const
Returns the thickness of this cell's sediment (total for all size classes, both consolidated and unconsolidated)
Definition at line 95 of file cell_layer.cpp.
dGetUnconsolidatedThickness()
double CRWCellLayer::dGetUnconsolidatedThickness (void) const
Returns the thickness of this cell's unconsolidated sediment (total for all size classes)
Definition at line 83 of file cell_layer.cpp.
pGetConsolidatedSediment()
CRWCellSediment * CRWCellLayer::pGetConsolidatedSediment (void)
Returns a pointer to the cell's consolidated sediment object.
Definition at line 41 of file cell_layer.cpp.
Referenced by CGeomCell::dGetTotConsCoarseThickConsiderNotch(), CGeomCell::dGetTotConsFineThickConsiderNotch(), and CGeomCell::dGetTotConsSandThickConsiderNotch().
pGetUnconsolidatedSediment()
CRWCellSediment * CRWCellLayer::pGetUnconsolidatedSediment (void)
Returns a pointer to the cell's unconsolidated sediment object.
Definition at line 35 of file cell_layer.cpp.
SetVolSedFraction()
void CRWCellLayer::SetVolSedFraction (double const)
Field Documentation
m_ConsolidatedSediment
CRWCellSediment CRWCellLayer::m_ConsolidatedSediment private
This cell's consolidated sediment object.
Definition at line 43 of file cell_layer.h.
Referenced by dGetCoarseConsolidatedThickness(), dGetConsolidatedThickness(), dGetFineConsolidatedThickness(), dGetSandConsolidatedThickness(), dGetTotalThickness(), and pGetConsolidatedSediment().
m_UnconsolidatedSediment
CRWCellSediment CRWCellLayer::m_UnconsolidatedSediment private
This cell's unconsolidated sediment object.
Definition at line 40 of file cell_layer.h.
Referenced by dGetCoarseUnconsolidatedThickness(), dGetFineUnconsolidatedThickness(), dGetSandUnconsolidatedThickness(), dGetTotalThickness(), dGetUnconsolidatedThickness(), and pGetUnconsolidatedSediment().
The documentation for this class was generated from the following files:
cell_layer.h
cell_layer.cpp